In [1]:
import requests
import json
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
from IPython.display import display
import time

## Organization Strategy: How Can We Store Info on Polyratings?

### Entities & Features
 
 Entities/Objects
 * Professors
 * Reviews 
 * Courses
 
 Attributes/Features
 * Grades earned by reviewers
 * The Year level (Freshman, Sophomore, etc.) of the reviewers
 * Course
 * Department
 * Professor Abilities 
     * Overall Rating
     * Presents Material Clearly
     * Understands Student Difficulties
 * Number of Reporting Evaluations/Reviews

### review_id:
Many of the statistics are based on the individual sample reviews. These are conveniently accompanied by a 'comment id' in the html of Polyratings.com. 

### prof_id: 
The professors each have their own review page and full statistical analysis page. Both of the urls for these pages end with a unique number. Let's use this as a professor id.

In [2]:
def get_prof_id(url): 
    '''
    Finds a Professor's Id, as specified in the url.
    Example: with the url: http://polyratings.com/eval.phtml?profid=2073
                prof_id is: 2073
    
    Args: 
        url (string)
    Returns:
        prof_id (int)
        
    '''
    prof_id = url.split('profid=')[-1]
    return int(prof_id)

# Start by Parsing Aggregate Data

In [3]:
def clean(words, letter_or_year=True, prof_id=0): 
    '''
    Cleans the Statistics from by Year and By Letter Grade
    
    Args: 
        words: (list): contains strings with the statistics inside.
        
        letter_or_year (bool): 
            True if parsing ratings by letter grades
            False if parsing ratings by year level
            
    Returns: 
        grades (dict): a dictionary of dictionaries that hold statistics. 
    
    '''
    
    grade_section = []
    
    if letter_or_year:
        for item in words: 
            #This is what we split on
            item = item.split('Receiving a Grade of \'')
            grade_section.append(item)
        
        
        grades = dict.fromkeys(['A', 'B', 'C', 'Credit','D', 'F', 'No Credit', 'N/A'])
       
    else: 
        for item in words: 
            #This is what we split on
            item = item.split('With a \'')
            grade_section.append(item)
            
        grades = dict.fromkeys(['Freshman', 'Sophomore', 'Junior', \
                                'Senior', '5th Year Senior', 'Graduate Student'])
        
    if len(grade_section) > 0:
        grade_section = grade_section[0] #The rest is negligible.

        #grade_section is now a list of strings
        for item in grade_section: 
            if letter_or_year:
                key=item[0]

                # We were only looking at the first character
                # We need the first 3 for N/A dict key
                if key == 'N':
                    if item[1] == 'o':
                        key = 'No Credit'
                    else:
                        key = 'N/A'

                if key == 'C' and item[1] == 'r':
                    key = 'Credit'

            else: 
                key = item.split('\' ')[0]

            if key in grades.keys(): 

                # Parse out the extra text strings. 
                # Only keep the ones with colons.
                start = 2
                end = 6
                stats = item.replace('\xa0', '').split('\n')[start: end]

                #Make a dict of each statistic and it's description
                d = dict(stat.split(":") for stat in stats)

                #Parse the types correctly
                for k in d.keys():
                    try:
                        d[k] = int(d[k])
                    except ValueError:
                        d[k] = float(d[k])

                #Assign the statistic dictionaries into the larger dictionary.
                grades[key] = d
    #             df.columns = df.columns.str.replace('Overall Grade','Overall Rating')
    else: 
        print('Professor ___ has nothing: ', prof_id)
    
    return grades #a dictionary of dictionaries

This function helps ensure that values are the correct type.

In [4]:
def parse_types(values):
    ''' Converts strings to floats or integers.
    Args: 
        list of strings
    Returns: 
        list containing floats and integers.
    '''
    
    parsed = []
    for value in values: 
        if '.' in value: 
            value = float(value)
        elif value == '': 
            value = 0
        else: 
            value = int(value)
        parsed.append(value)
        
    return parsed

# Scrape Statistics
get_sample_stats extracts the mean, median, mode, and standard deviation for a professor on his/her full statistical analysis page. Here is an example page: http://polyratings.com/stats.phtml?profid=2073

In [5]:
def get_sample_stats(table_tag):
    
    '''
        Extracts mean, median, mode, and standard deviation for each professor. 
        
        Args: 
            table (td tag): holds tags within with data.
        
        Returns: 
            a DataFrame holding the statistics. 
    
    '''
    
    b_tags = table_tag.findAll('b')
    tds = []
    
    #Find td tags that follow b tags
    for b in b_tags: 
        tds.append(b.findNext('td'))
        
    #Just need the last four items.
    tds = tds[-4:]
    
    tds = [stat.text for stat in tds]
    
    stat_d = {}
    stat_d['mean'], stat_d['median'], stat_d['mode'], stat_d['std_dev'] = \
        parse_types(tds) 

    return pd.DataFrame.from_dict(data=stat_d, orient='index')

# Scrape Professor's Overall Statistics: 
## * Overall rating
## * Ability to present material clearly
## * Ability to understand student difficulties

In [12]:
def get_prof_stats(full_stat_url):
    '''Returns a list of DataFrames of statistics scraped from a professor's
        full stat analysis url
    
        Args: 
            full_stat_url (string): the link to the professor's polyratings
        
        Returns:
            list 
            [prof_df (DataFrame): holds general info about professor
            prof_stats DataFrame]: holds statistics about professor
    
    '''
    
    prof_df = {}
    prof_stats = {}
    
    r = requests.get(full_stat_url)
    soup = BeautifulSoup(r.text, 'html.parser')
    
    # Professor Name and Department(s)
    fonts = soup.findAll('font') #each is type <class 'bs4.element.Tag'>
    name_font = fonts[2].text.replace('\n', ' ') 
    dept_font = fonts[3].text.replace('\n', ' ').split(' Department')[0]
    
    prof_df['Name'] = name_font
    prof_df['Dept'] = dept_font
    
    prof_id = get_prof_id(full_stat_url)
    prof_df['prof_id'] = prof_id
    
    # Professor Statistics
    stats = soup.findAll('table') 
    #we'll have to sort through different ones.
    # stats[2] is the name and dept table
    
    #Sections of HTML
    overall_t = stats[3]
    ability_to_present_t = stats[4]
    ability_to_understand_t = stats[5]
    #Total number of evaluations
    prof_df['Reporting Evaluations'] = int(overall_t.findAll('td', width='15%')[0].text)

    #Get Sample Stats for each table
    overall_sample_stats = get_sample_stats(overall_t)
    ability_to_present_sample_stats = get_sample_stats(ability_to_present_t)
    ability_to_understand_sample_stats = get_sample_stats(ability_to_understand_t)

    prof_stats = pd.merge(left=overall_sample_stats, \
                          right=ability_to_present_sample_stats, \
                         left_index=True, right_index=True, how='outer')
    prof_stats = pd.merge(left=prof_stats, right=ability_to_understand_sample_stats, \
                         left_index=True, right_index=True, how='outer')
    
    prof_stats = pd.DataFrame.transpose(prof_stats)
    prof_stats['rating_type'] = ['Overall Rating', 'Presents Material Clearly', \
                                 'Recognizes Student Difficulties']
    prof_stats['prof_id'] = prof_id
    prof_stats.index = ([0, 1, 2])
    
    prof_stats[['median', 'mode']] = prof_stats[['median', 'mode']].astype(int)
    prof_df = pd.DataFrame(prof_df, index=[0]).set_index(['prof_id'])

    # A list of dataframes that describe a professor
    return [prof_df, prof_stats]

# Scrape data from a full statistical analysis page including:
## * Overall statistics (by calling get_prof_stats), 
## * Mean rating grouped by grade earned, and 
## * Mean rating grouped by reviewers' year level.

In [13]:
def get_ratings(url):
    '''
    Calls functinos to get a list of DataFrames representing statistics for a professor. 
    
    Args: 
        url (string), the professor's statistical analysis page.
    Returns: 
        A list of DataFrames: 
         * prof_df: 
             the Professor DataFrame specifying name, number of evaluations, department
         * prof_stats:
             the Professor's Overall Rating Statistics
         * letter_grade_ratings:
             the Professor's Rating Statistics Based on Reviewer's Letter Grade Earned
         * year_grade_ratings:
             the Professor's Rating Statistics Based on Reviewer's Year Grade Earned
    
    '''
    
    prof_id = get_prof_id(url)
    print('\nProfessor: ', prof_id)
    
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    
    children = soup.getText().split('Polyratings.com')
    letter_grade_evals = children[3:4]
    year_grade_evals = children[4:5]
    
#     print("Letter_grade_evals in get_ratings()", letter_grade_evals)
    
    if len(letter_grade_evals) > 0:
    
        letter_grade_ratings = \
            pd.DataFrame(clean(letter_grade_evals, letter_or_year=True, prof_id=prof_id))
            
        letter_grade_ratings = \
            letter_grade_ratings.rename(index={'Overall Grade': 'Overall Rating'})
            
        letter_grade_ratings['prof_id'] = prof_id

        year_grade_ratings = \
            pd.DataFrame(clean(year_grade_evals, letter_or_year=False, prof_id=prof_id))
            
        year_grade_ratings = \
            year_grade_ratings.rename(index={'Overall Grade': 'Overall Rating'})
            
        year_grade_ratings['prof_id'] = prof_id

        #Get the mean, median, mode, std_dev of all ratings
        prof_df, prof_stats = get_prof_stats(url)

        return [prof_df, prof_stats, letter_grade_ratings, year_grade_ratings]
    else: 
        return ValueError()

# Collect Data on Each Professor
## * Convert professor page urls to professor full statistical analysis page urls. 
## * Loop through and get_ratings on each professor.

In [14]:
def get_full_stat_urls(professor_paths): 
    '''Helper function, gets links to professors' full statistical analysis pages. 
        
       Args: 
           professor_paths (list of strings): 
               each is a link to a prof's polyratings page.
        
       Returns: 
           full_stat_paths (list of strings): each is a link to a prof's 
               full stat analysis page.
    '''
    
    # The trick is that the prof url might be: 
        # http://polyratings.com/eval.phtml?profid=2073
        
    # while the corresponding full stat analysis url is: 
        # http://polyratings.com/stats.phtml?profid=2073
        
    # Replace the word 'stats' with 'stats'
    
    return [p.replace('eval', 'stats') for p in professor_paths]


def get_all_professors_stats(professor_urls):

    '''Helper function: 
       Slowly collects data on each professor on polyratings.
       Calls parser functions to clean the data.
       
       Args: 
           professor_urls (list): links to professors' polyratings pages.
       Returns: 
           info from get_ratings(full_stat_url) for each professor
           all_prof_stats_dfs (list of lists of DataFrames)
               each item in list is a list containing 4 DataFrames
                    [[first_prof_df, 
                    first_prof_stats, 
                    first_prof_stats_by_letter, 
                    first_prof_stats_by_grade]
                    
                    [second_prof_df, 
                    second_prof_stats, 
                    second_prof_stats_by_letter, 
                    second_prof_stats_by_grade]
                    ...]
            
    '''
    full_stat_urls = get_full_stat_urls(professor_urls)
    all_prof_stats_dfs = []
    
    #Every so often, call data scraping functions on each url.
    for url in full_stat_urls:
        time.sleep(1.0)
        
        full_stat_url = url.replace('eval', 'stats')
        
        #Get the basic prof info as well as mean, median, mode, std_dev of all ratings
        all_prof_stats_dfs.append(get_ratings(full_stat_url))
        
    return all_prof_stats_dfs

## Start by scraping a list of professor page urls.

In [55]:
professor_list_url = "http://polyratings.com/list.phtml"

def get_professor_urls():
    '''Gets links to professor polyratings pages. 
    
       Returns: 
           professor_paths (list of strings): each is a link.
    '''
    professor_list_url
    index = requests.get(professor_list_url)
    soup = BeautifulSoup(index.text, 'html.parser')
    professor_paths = []
    
    for a in soup.findAll('a'):
        if 'eval' in a['href']:
            professor_paths.append(a['href'])
      
    return professor_paths

## Test the code with one professor:  Clint Staley

In [16]:
clint = 'http://polyratings.com/stats.phtml?profid=620'
clint_df, clint_stats, clint_stats_by_grade, clint_stats_by_year = get_ratings(clint)

Professor:  620

In [17]:
clint_df

                     Dept          Name  Reporting Evaluations
prof_id
620      Computer Science  Clint Staley                    179

In [18]:
clint_stats

   median   mean  std_dev  mode                      rating_type  prof_id
0       0  3.034    1.410     4                   Overall Rating      620
1       0  3.251    1.272     4        Presents Material Clearly      620
2       0  2.872    1.446     4  Recognizes Student Difficulties      620

In [19]:
clint_stats_by_grade

,A,B,C,Credit,D,F,N/A,No Credit,prof_id
Overall Rating,3.554,2.692,2.647,None,0.75,2.267,2.364,3,620
Presents Material Clearly,3.717,2.974,3.059,None,1.50,2.200,2.636,4,620
Recognizes Student Difficulties,3.435,2.692,2.294,None,0.25,2.000,1.909,2,620
Reporting Evaluations,92.000,39.000,17.000,None,4.00,15.000,11.000,1,620

In [20]:
print(clint_stats_by_grade['B'][0], type(clint_stats_by_grade['B'][0]))
assert type(clint_stats_by_grade['B'][0]) == np.float64

2.692 <class 'numpy.float64'>

In [21]:
clint_stats_by_year

,5th Year Senior,Freshman,Graduate Student,Junior,Senior,Sophomore,prof_id
Overall Rating,3.125,3.74,2.667,2.511,2.750,2.927,620
Presents Material Clearly,3.750,3.68,3.333,2.894,3.063,3.145,620
Recognizes Student Difficulties,2.750,3.56,2.333,2.426,2.375,2.818,620
Reporting Evaluations,8.000,50.00,3.000,47.000,16.000,55.000,620

In [22]:
assert clint_stats_by_year['Freshman'][0] == 3.740

# Let's Try Two Professors!
### None values occur when Polyratings does not have data for those sections.

In [23]:
#Test first and last urls
professor_urls = get_professor_urls()[1:]
first = professor_urls[0] #first is a string
last = professor_urls[-1]
two_professors = [first, last]

In [24]:
assert first == 'http://polyratings.com/eval.phtml?profid=2073'
assert last == 'http://polyratings.com/eval.phtml?profid=728'

In [25]:
prof_dfs_list = get_all_professors_stats(two_professors)
# profs_dfs_list is a list of lists of dataframes. 

for i in prof_dfs_list: 
    print('\nAnother Professor\'s List of Data Frames: ', i[0]['Name'])
    for j in i:
        display(j)
    print('\n')

Professor:  2073

Professor:  728

Another Professor's List of Data Frames:  prof_id
2073    Christina Abel
Name: Name, dtype: object

                               Dept            Name  Reporting Evaluations
prof_id
2073     Chemistry and Biochemistry  Christina Abel                     32

   median   mean  std_dev  mode                      rating_type  prof_id
0       4  3.563    0.556     4                   Overall Rating     2073
1       4  3.594    0.551     4        Presents Material Clearly     2073
2       4  3.563    0.658     4  Recognizes Student Difficulties     2073

,A,B,C,Credit,D,F,N/A,No Credit,prof_id
Overall Rating,3.769,3.222,3.75,None,3,None,3,None,2073
Presents Material Clearly,3.769,3.222,3.75,None,3,None,4,None,2073
Recognizes Student Difficulties,3.692,3.222,3.75,None,4,None,3,None,2073
Reporting Evaluations,13.000,9.000,8.00,None,1,None,1,None,2073

,5th Year Senior,Freshman,Graduate Student,Junior,Senior,Sophomore,prof_id
Overall Rating,None,3.500,None,4.000,3.333,3.583,2073
Presents Material Clearly,None,3.714,None,3.667,3.333,3.500,2073
Recognizes Student Difficulties,None,3.571,None,4.000,3.667,3.417,2073
Reporting Evaluations,None,14.000,None,3.000,3.000,12.000,2073

Another Professor's List of Data Frames:  prof_id
728    Dick Zweifel
Name: Name, dtype: object

                 Dept          Name  Reporting Evaluations
prof_id
728      Architecture  Dick Zweifel                     16

   median   mean  std_dev  mode                      rating_type  prof_id
0       1  1.625    1.317     1                   Overall Rating      728
1       2  2.375    1.111     2        Presents Material Clearly      728
2       2  1.875    1.166     1  Recognizes Student Difficulties      728

,A,B,C,Credit,D,F,N/A,No Credit,prof_id
Overall Rating,None,None,None,1.083,None,4,3.000,None,728
Presents Material Clearly,None,None,None,1.917,None,4,3.667,None,728
Recognizes Student Difficulties,None,None,None,1.333,None,4,3.333,None,728
Reporting Evaluations,None,None,None,12.000,None,1,3.000,None,728

,5th Year Senior,Freshman,Graduate Student,Junior,Senior,Sophomore,prof_id
Overall Rating,4,1.231,4,2,None,None,728
Presents Material Clearly,4,2.154,4,2,None,None,728
Recognizes Student Difficulties,4,1.538,4,2,None,None,728
Reporting Evaluations,1,13.000,1,1,None,None,728

In [26]:
this_professor = prof_dfs_list[0]
last_professor = prof_dfs_list[1]

#Test the first table
assert type(this_professor[0].index.values[0]) == np.int64
assert type(this_professor[0]['Dept'].values[0]) == str
assert type(this_professor[0]['Reporting Evaluations'].values[0]) == np.int64
assert type(this_professor[0]['Name'].values[0]) == str

#Test the second table
assert type(this_professor[1]['mode'].values[0]) == np.int64
assert type(this_professor[1]['median'].values[0]) == np.int64
assert type(this_professor[1]['mean'].values[0]) == np.float64
assert type(this_professor[1]['rating_type'].values[0]) == str
assert type(this_professor[1]['prof_id'].values[0]) == np.int64

#Test the third table
assert type(this_professor[2]['A'].values[0]) == np.float64
assert type(this_professor[2]['B'].values[0]) == np.float64
assert type(this_professor[2]['C'].values[0]) == np.float64
assert type(this_professor[2]['D'].values[0]) == np.float64
assert type(this_professor[2]['N/A'].values[0]) == np.float64
assert type(this_professor[2]['prof_id'].values[0]) == np.int64

#Test the fourth table
print(type(this_professor[3]['5th Year Senior'].values[0]))
assert type(last_professor[3]['5th Year Senior'].values[0]) == np.float64

assert type(this_professor[3]['Freshman'].values[0]) == np.float64
assert type(this_professor[3]['Sophomore'].values[0]) == np.float64
assert type(this_professor[3]['Junior'].values[0]) == np.float64
assert type(this_professor[3]['prof_id'].values[0]) == np.int64

<class 'NoneType'>

## We Want 4 Total DataFrames that Hold This Info for All Professors
## -> Merge Each Professors' DataFrames Together
## -> The Professor Ids Identify unique professors in DataFrames

In [27]:
# Concatenate dataframes
def merge_professors(profs_dfs_list):
    
    '''
    Takes a list of professors' lists of DataFrames. 
    Joins each DataFrame into 
     Args: 
         profs_dfs_list (list of lists of DataFrames)
               each item in list is a list containing 4 DataFrames
            [[first_prof_df, first_prof_stats, 
            first_prof_stats_by_letter, 
            first_prof_stats_by_grade]
            [second_prof_df, second_prof_stats, 
            second_prof_stats_by_letter, 
            second_prof_stats_by_grade]
            ...]
            
    Returns:
        
        a list of 4 DataFrames with respective info for all professors. 
            
    
    '''
    
    iterprofs = iter(profs_dfs_list)
    
    first_prof = next(iterprofs)
    if type(first_prof[0]) == pd.DataFrame:
        profs_df = first_prof[0]
        print(profs_df)
    if type(first_prof[1]) == pd.DataFrame:
        profs_stats = first_prof[1]
        print(profs_stats)
    
    profs_stats_by_grade = first_prof[2]
    print(profs_stats_by_grade)
    
    profs_stats_by_year = first_prof[3]
    print(profs_stats_by_year)
    
    #Keep track of the profs_stats_by_letters without concatenating them.
    profs_stats_by_grade_list = [first_prof[2]]
    
    #Iterate through each professor
    for professor_list in iterprofs: 
        if type(professor_list) == list:
            profs_df = pd.concat([profs_df, professor_list[0]])
            profs_stats = pd.concat([profs_stats, \
                                     professor_list[1]]).reset_index(drop=True)
            
            profs_stats_by_letter = pd.concat([profs_stats_by_grade, \
                                               professor_list[2]])
            profs_stats_by_grade = pd.concat([profs_stats_by_year, \
                                              professor_list[3]], \
                                             join='outer', axis=0)
        
            profs_stats_by_grade_list.append(professor_list[2])

    return [profs_df, profs_stats, profs_stats_by_letter, \
            profs_stats_by_grade, profs_stats_by_grade_list]

## Merged Professors' Data Frames

In [28]:
profs_df, profs_stats, profs_stats_by_grade, \
    profs_stats_by_year, profs_stats_by_grade_list = merge_professors(prof_dfs_list)

                               Dept            Name  Reporting Evaluations
prof_id
2073     Chemistry and Biochemistry  Christina Abel                     32
   median   mean  std_dev  mode                      rating_type  prof_id
0       4  3.563    0.556     4                   Overall Rating     2073
1       4  3.594    0.551     4        Presents Material Clearly     2073
2       4  3.563    0.658     4  Recognizes Student Difficulties     2073
                                      A      B     C Credit  D     F  N/A  \
Overall Rating                    3.769  3.222  3.75   None  3  None    3
Presents Material Clearly         3.769  3.222  3.75   None  3  None    4
Recognizes Student Difficulties   3.692  3.222  3.75   None  4  None    3
Reporting Evaluations            13.000  9.000  8.00   None  1  None    1

                                No Credit  prof_id
Overall Rating                       None     2073
Presents Material Clearly            None     2073
Recognizes Student Difficulties      None     2073
Reporting Evaluations                None     2073
                                5th Year Senior  Freshman Graduate Student  \
Overall Rating                             None     3.500             None
Presents Material Clearly                  None     3.714             None
Recognizes Student Difficulties            None     3.571             None
Reporting Evaluations                      None    14.000             None

                                 Junior  Senior  Sophomore  prof_id
Overall Rating                    4.000   3.333      3.583     2073
Presents Material Clearly         3.667   3.333      3.500     2073
Recognizes Student Difficulties   4.000   3.667      3.417     2073
Reporting Evaluations             3.000   3.000     12.000     2073

In [29]:
profs_df

                               Dept            Name  Reporting Evaluations
prof_id
2073     Chemistry and Biochemistry  Christina Abel                     32
728                    Architecture    Dick Zweifel                     16

In [30]:
profs_stats

   median   mean  std_dev  mode                      rating_type  prof_id
0       4  3.563    0.556     4                   Overall Rating     2073
1       4  3.594    0.551     4        Presents Material Clearly     2073
2       4  3.563    0.658     4  Recognizes Student Difficulties     2073
3       1  1.625    1.317     1                   Overall Rating      728
4       2  2.375    1.111     2        Presents Material Clearly      728
5       2  1.875    1.166     1  Recognizes Student Difficulties      728

In [31]:
profs_stats_by_grade

,A,B,C,Credit,D,F,N/A,No Credit,prof_id
Overall Rating,3.769,3.222,3.75,NaN,3,NaN,3.000,NaN,2073
Presents Material Clearly,3.769,3.222,3.75,NaN,3,NaN,4.000,NaN,2073
Recognizes Student Difficulties,3.692,3.222,3.75,NaN,4,NaN,3.000,NaN,2073
Reporting Evaluations,13.000,9.000,8.00,NaN,1,NaN,1.000,NaN,2073
Overall Rating,NaN,NaN,NaN,1.083,NaN,4,3.000,NaN,728
Presents Material Clearly,NaN,NaN,NaN,1.917,NaN,4,3.667,NaN,728
Recognizes Student Difficulties,NaN,NaN,NaN,1.333,NaN,4,3.333,NaN,728
Reporting Evaluations,NaN,NaN,NaN,12.000,NaN,1,3.000,NaN,728

In [32]:
profs_stats_by_year

,5th Year Senior,Freshman,Graduate Student,Junior,Senior,Sophomore,prof_id
Overall Rating,NaN,3.500,NaN,4.000,3.333,3.583,2073
Presents Material Clearly,NaN,3.714,NaN,3.667,3.333,3.500,2073
Recognizes Student Difficulties,NaN,3.571,NaN,4.000,3.667,3.417,2073
Reporting Evaluations,NaN,14.000,NaN,3.000,3.000,12.000,2073
Overall Rating,4,1.231,4,2.000,NaN,NaN,728
Presents Material Clearly,4,2.154,4,2.000,NaN,NaN,728
Recognizes Student Difficulties,4,1.538,4,2.000,NaN,NaN,728
Reporting Evaluations,1,13.000,1,1.000,NaN,NaN,728

In [33]:
profs_stats_by_grade_list[0:2]

[                                      A      B     C Credit  D     F  N/A  \
 Overall Rating                    3.769  3.222  3.75   None  3  None    3
 Presents Material Clearly         3.769  3.222  3.75   None  3  None    4
 Recognizes Student Difficulties   3.692  3.222  3.75   None  4  None    3
 Reporting Evaluations            13.000  9.000  8.00   None  1  None    1

                                 No Credit  prof_id
 Overall Rating                       None     2073
 Presents Material Clearly            None     2073
 Recognizes Student Difficulties      None     2073
 Reporting Evaluations                None     2073  ,
                                     A     B     C  Credit     D  F    N/A  \
 Overall Rating                   None  None  None   1.083  None  4  3.000
 Presents Material Clearly        None  None  None   1.917  None  4  3.667
 Recognizes Student Difficulties  None  None  None   1.333  None  4  3.333
 Reporting Evaluations            None  None  None  12.000  None  1  3.000

                                 No Credit  prof_id
 Overall Rating                       None      728
 Presents Material Clearly            None      728
 Recognizes Student Difficulties      None      728
 Reporting Evaluations                None      728  ]

----------------------------------------------------------------------------------------------

# Scrape and Parse The Professors' Individual Reviews

In [34]:
def clean_review(review):
    '''
    Takes in a review bs4.element.Tag, which is a tr tag with review information
    Puts info into dictionaries, appended into a list.
    
    Args: 
        review (bs4.element.Tag): representing a tr tag.
    
    Returns:
        dictionaries (list): list of dictionaries.
    
    '''
    
    review_dict = {}
    
    #Parse the Review Id
    review_id_tag = review.findNext('a')
    review_id = int(str(review_id_tag).strip(' --></a>').split(' ')[-1])
    review_dict['review_id'] = review_id
    
    
    #Parse the Year and Grade of the student who wrote this review
    br_tags = review.find(['br'])
    years = str(br_tags).split('<br>')[1:3]
    
    #If there is year and grade info, parse it.
    if len(years) > 0:
        years = [x.strip('\n   ') for x in years]
        review_dict['Year'] = years[0]

        grade = years[1].rstrip('</b>').split(' <b>')
        review_dict['Grade'] = grade[1]
    
    #If there is a course name, parse it.
    review_year_tags = review.findAll(['b', 'a'])
    if len(review_year_tags) > 0:
        review_dict['Course'] = \
            str(review_year_tags[1]).rstrip('</a></b>').split('>')[-1]
        
        
    #Now parse the review 
    review_text = str(review).split('</td>')
    if len(review_text) > 1: 
        review_text = review_text[-2]
        
        if review_text.strip() != '<tr><td bgcolor="#ffffff" colspan="3">':
            review_text = \
                review_text.strip().lstrip('<td align="left" valign="top" \
                                            width="79%">').strip()
                
            review_dict['Review'] = review_text
    
    df =  pd.DataFrame.from_dict(review_dict, orient='index')
    
    return df.transpose()

def get_prof_reviews(page_url):
    
    '''
        Calls cleaner functions to tidy up reviews scraped from webpages.
        
        Args: 
            page_url (string): a link to professor's polyratings page.
            
        Returns: 
            reviews_df (DataFrame) a reviews DataFrame for that professor.
    
    '''
    
    r = requests.get(page_url)
    soup = BeautifulSoup(r.text, 'html.parser')
    prof_id = get_prof_id(page_url)
    
    table_rows = soup.findAll('tr')
    table_rows = table_rows
    
    reviews = []
    i = 0
    #clean up each row
    for row in table_rows[6:-3]:
        if i%2 == 0:
            row_df = clean_review(row)

            #if it's a review, add it to the review frame
            if len(row_df.columns) > 0: 
                reviews.append(row_df)
        i+=1 
    
    #connect review frames
    print('Professor Id: ', prof_id)
    if len(reviews) > 0:
        reviews_df = pd.concat(reviews)
        #tack on professor id.
        reviews_df['prof_id'] = prof_id
        
        return reviews_df
    else: 
        print('No reviews to concatenate.')


def get_all_profs_reviews(review_page_urls): 
    '''Helper function: 
       Slowly collects reviews on each professor on polyratings.
       Calls parser functions to clean the data.
       
       Args: 
           review_page_urls (list): links to professors' polyratings pages.
           
       Returns: 
           info from get_prof_reviews(page_url) for each professor
           reviews(list of lists of DataFrames)
               each item in list is a list containing 4 DataFrames
                    [[]
                    []
                    ...]
    '''

    professors_reviews = []
    
    #Every so often, call data scraping functions on each url.
    for url in review_page_urls:
        
        time.sleep(1.0)
        p_reviews = get_prof_reviews(url)
        if len(p_reviews) > 0:
            professors_reviews.append(p_reviews)
        
    return professors_reviews


## Let's Test Getting Reviews for Just One Professor

In [35]:
from IPython.display import display

reviews = get_prof_reviews(two_professors[0]).reset_index(drop=True)

assert type(reviews['Grade'].values[0]) == str
assert type(reviews['Course'].values[0]) == str
assert type(reviews['Year'].values[0]) == str
assert type(reviews['Review'].values[0]) == str
assert type(reviews['review_id'].values[0]) == int
assert type(reviews['prof_id'].values[0]) == np.int64

reviews.head()

Professor Id:  2073

,Review,Grade,review_id,Course,Year,prof_id
0,anytext or 1=1',B,54423,CHEM 111,Junior,2073
1,Abel is a pretty good chem teacher. Her notes...,B,35061,CHEM 125,Freshman,2073
2,"Dr. Abel, is very helpful and approachable in ...",C,34766,CHEM 125,Senior,2073
3,Talks nonstop for 3/4 of the class period and ...,B,34495,CHEM 124,Freshman,2073
4,"To do well in Abel's class, the key is practic...",A,34359,CHEM 124,Freshman,2073

## Tack on the Overall Professor Ratings by Student Reviewer's Letter Grade Earned

In [36]:
def concat_prof_by_letter(prof_stats_by_letter, my_reviews):
    
    '''
    Adds the professor's overall ratings to each row, 
    depending on the grade earned by that review.
    
    Keeping all of this code in one function eliminates 
    the alternative predicament of passing many parameters 
    to a small functions.
    
    Args: 
        prof_stats_by_letter (DataFrame): 
            Shows the overall ratings for that professor as rated by the 
            groups of students, segregated by grade earned.
        
        my_reviews (DataFrame):
            DataFrame of reviews for the professor. 
    Returns: 
        A ratings DataFrame with all reviews for a professor and overall ratings. 
    
    
    '''
    A_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'A'])
    A_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['A']['Presents Material Clearly']
        
    A_reviews['Overall Rating'] = prof_stats_by_letter['A']['Overall Rating']
    A_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['A']['Recognizes Student Difficulties']
        
    A_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['A']['Reporting Evaluations']

    B_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'B'])
    B_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['B']['Presents Material Clearly']
    B_reviews['Overall Rating'] = prof_stats_by_letter['B']['Overall Rating']
    B_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['B']['Recognizes Student Difficulties']
    B_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['B']['Reporting Evaluations']

    C_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'C'])
    C_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['C']['Presents Material Clearly']
    C_reviews['Overall Rating'] = prof_stats_by_letter['C']['Overall Rating']
    C_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['C']['Recognizes Student Difficulties']
    C_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['C']['Reporting Evaluations']

    D_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'D'])
    D_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['D']['Presents Material Clearly']
    D_reviews['Overall Rating'] = prof_stats_by_letter['D']['Overall Rating']
    D_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['D']['Recognizes Student Difficulties']
    D_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['D']['Reporting Evaluations']

    F_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'F'])
    F_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['F']['Presents Material Clearly']
    F_reviews['Overall Rating'] = prof_stats_by_letter['F']['Overall Rating']
    F_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['F']['Recognizes Student Difficulties']
    F_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['F']['Reporting Evaluations']

    NA_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'N/A'])
    NA_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['N/A']['Presents Material Clearly']
    NA_reviews['Overall Rating'] = prof_stats_by_letter['N/A']['Overall Rating']
    NA_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['N/A']['Recognizes Student Difficulties']
    NA_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['N/A']['Reporting Evaluations']

    NoCredit_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'No Credit'])
    NoCredit_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['No Credit']['Presents Material Clearly']
    NoCredit_reviews['Overall Rating'] = \
        prof_stats_by_letter['No Credit']['Overall Rating']
    NoCredit_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['No Credit']['Recognizes Student Difficulties']
    NoCredit_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['No Credit']['Reporting Evaluations']
  
    Credit_reviews = pd.DataFrame(my_reviews[my_reviews.Grade == 'Credit'])
    Credit_reviews['Presents Material Clearly'] = \
        prof_stats_by_letter['Credit']['Presents Material Clearly']
    Credit_reviews['Overall Rating'] = \
        prof_stats_by_letter['Credit']['Overall Rating']
    Credit_reviews['Recognizes Student Difficulties'] = \
        prof_stats_by_letter['Credit']['Recognizes Student Difficulties']
    Credit_reviews['Reporting Evaluations'] = \
        prof_stats_by_letter['Credit']['Reporting Evaluations']

    assert type(A_reviews) == pd.DataFrame
    assert type(B_reviews) == pd.DataFrame
    assert type(C_reviews) == pd.DataFrame
    assert type(D_reviews) == pd.DataFrame
    assert type(F_reviews) == pd.DataFrame
    assert type(Credit_reviews) == pd.DataFrame
    assert type(NA_reviews) == pd.DataFrame
    assert type(NoCredit_reviews) == pd.DataFrame

    dataframes = []
    if len(A_reviews) > 0: 
        dataframes.append(A_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(B_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(C_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(D_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(F_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(NA_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(Credit_reviews)
    if len(A_reviews) > 0: 
        dataframes.append(NoCredit_reviews)
    if len(dataframes) > 0:
        return pd.concat(dataframes)
    else:
        return np.nan

In [37]:
def get_reviews_by_grade(professor_reviews, profs_stats_by_letter_list):
    '''
        Gets a Reviews DataFrame with Overall Professor Ratings 
        by Letter Grade, for all Professors.
        
        Args: 
            professor_reviews (list of DataFrames): 
                Each in the list holds ratings for a professor.
                
            profs_stats_by_letter_list (list of DataFrames):
                Each in the list holds mean ratings for a professor 
                based on Letter Grade earned by reviewer.
                
        Returns: 
            A Reviews DataFrame, indexed by review_ids, 
            showing Professors Overall Ratings based on 
            Grades, Grades, Year, Course, Prof_id, etc
    '''
    
    concatenateds = []
    n = len(profs_stats_by_letter_list)
    
    if n == len(professor_reviews):
        print('n = ', n)
        for letter_df, rev_df in zip(profs_stats_by_letter_list, professor_reviews):
            return_val = concat_prof_by_letter(letter_df, rev_df)
            if return_val is not np.nan:
                concatenateds.append(return_val)
        return pd.concat(concatenateds).reset_index(drop=True).set_index('review_id')
    else: 
        print('Lengths of lists of DataFrames are not compatible.')

## Get Reviews Table For All Professors
## Set the Index to the Review_Id

In [38]:
my_reviews = get_all_profs_reviews(two_professors)
reviews_by_grade = get_reviews_by_grade(my_reviews, profs_stats_by_grade_list)
reviews_by_grade

Professor Id:  2073
Professor Id:  728
n =  2

,Review,Grade,Course,Year,prof_id,Presents Material Clearly,Overall Rating,Recognizes Student Difficulties,Reporting Evaluations
review_id,,,,,,,,,
34359,"To do well in Abel's class, the key is practic...",A,CHEM 124,Freshman,2073,3.769,3.769,3.692,13
34176,Great professor! I learned a lot in her class....,A,CHEM 127,Freshman,2073,3.769,3.769,3.692,13
34130,good,A,CHEM 124,Senior,2073,3.769,3.769,3.692,13
34073,Foxy.,A,CHEM 125,Sophomore,2073,3.769,3.769,3.692,13
34023,Abel is an amazing teacher. I think anyone sh...,A,CHEM 124,Sophomore,2073,3.769,3.769,3.692,13
33755,Dr. Abel is a fantastic teacher. She presents ...,A,CHEM 124,Freshman,2073,3.769,3.769,3.692,13
33725,Excellent.,A,CHEM 125,Sophomore,2073,3.769,3.769,3.692,13
33448,SMOKING HOT. Great teacher too. No Hw. Just...,A,CHEM 125,Junior,2073,3.769,3.769,3.692,13
33145,"She's a great teacher, seems real nervous at f...",A,CHEM 127,Sophomore,2073,3.769,3.769,3.692,13
31992,Abel is amazing. She is really good at realizi...,A,CHEM 124,Freshman,2073,3.769,3.769,3.692,13
31660,Dr. Abel is a great chem prof. I would recomme...,A,CHEM 124,Freshman,2073,3.769,3.769,3.692,13
30100,Abel's class is doable but very tedious. Her t...,A,CHEM 127,Sophomore,2073,3.769,3.769,3.692,13
29539,She is an excellent professor. She really pre...,A,CHEM 125,Freshman,2073,3.769,3.769,3.692,13
54423,anytext or 1=1',B,CHEM 111,Junior,2073,3.222,3.222,3.222,9
35061,Abel is a pretty good chem teacher. Her notes...,B,CHEM 125,Freshman,2073,3.222,3.222,3.222,9
34495,Talks nonstop for 3/4 of the class period and ...,B,CHEM 124,Freshman,2073,3.222,3.222,3.222,9
33034,an amazing professor. her worksheets really he...,B,CHEM 124,Freshman,2073,3.222,3.222,3.222,9
31798,Abel is ok. She makes some mistakes during lec...,B,CHEM 127,Sophomore,2073,3.222,3.222,3.222,9
31425,"She acts nervous, and like the comment before ...",B,CHEM 124,Senior,2073,3.222,3.222,3.222,9
30204,"Good prof, really nice. Helpful during office...",B,CHEM 124,Sophomore,2073,3.222,3.222,3.222,9
29886,"I had Dr. Abel a year ago as a freshman, but P...",B,CHEM 124,Freshman,2073,3.222,3.222,3.222,9
29666,Everything for this class was straightforward....,B,CHEM 125,Sophomore,2073,3.222,3.222,3.222,9
34766,"Dr. Abel, is very helpful and approachable in ...",C,CHEM 125,Senior,2073,3.750,3.750,3.750,8
34305,"She's a great teacher, I found the 3 midterms ...",C,CHEM 124,Freshman,2073,3.750,3.750,3.750,8
33750,Dr. Abel is extremely helpful at recognizing s...,C,CHEM 124,Junior,2073,3.750,3.750,3.750,8
33517,Professor Abel is an amazing teacher. She know...,C,CHEM 125,Sophomore,2073,3.750,3.750,3.750,8
33108,I took Professor Abel my first quarter as a fr...,C,CHEM 127,Sophomore,2073,3.750,3.750,3.750,8
32537,she is amazing. i nv have appreciated a teache...,C,CHEM 127,Sophomore,2073,3.750,3.750,3.750,8
31366,Christina was a pretty good teacher and I enjo...,C,CHEM 124,Freshman,2073,3.750,3.750,3.750,8
30068,Abel is amazing! Presents the material clearly...,C,CHEM 127,Freshman,2073,3.750,3.750,3.750,8
33907,I could've done better in this class but I jus...,D,CHEM 127,Freshman,2073,3.000,3.000,4.000,1
31795,great. and very nice. very approachable,N/A,CHEM 127,Sophomore,2073,4.000,3.000,3.000,1

## Use the Index to the Review_Id to Access Reviews

In [39]:
#You can do this for each dataframe in the list my_reviews

reviews_by_grade.loc[35061]

Review                             Abel is a pretty good chem teacher.  Her notes...
Grade                                                                              B
Course                                                                      CHEM 125
Year                                                                        Freshman
prof_id                                                                         2073
Presents Material Clearly                                                      3.222
Overall Rating                                                                 3.222
Recognizes Student Difficulties                                                3.222
Reporting Evaluations                                                              9
Name: 35061, dtype: object

In [40]:
reviews_by_grade.loc[35061]['Review']

"Abel is a pretty good chem teacher.  Her notes are extremely well organized so it's really easy to go back and study before exams.  Unfortunately her class was at 7AM which may be why I found it boring.  Really nice, and super helpful.  Her tests are challenging but not impossible and you can get an A if you study for them.  DO THE WORKBOOKS, a lot of the problems and questions on her exams come straight out of the workbooks.  Also, she likes to give our a lot of supplemental handouts to go with her notes, STAPLE them to the corresponding page in your notes.  They are really helpful for your labs and quizzes but they are also really easy to lose or get mixed up."

----------------------------------------------------------------------------------------------

# Which DataFrames should we write to a JSON?
profs_df, profs_stats, profs_stats_by_grade, profs_stats_by_year, profs_stats_by_letter_list = merge_professors(prof_dfs_list)

Let's include the following:
* profs_df
    Basic Professor info (name, dept, #reviews)
* profs_stats
    Rating Averages, Standard Deviations, Median, Means per professor id.
* profs_stats_by_grade_list
    list of prof_stats_by_grade DataFrames, rather than a concatenated DataFrame
* reviews_by_grade
    profs_stats_by_grade per review id, well organized.
    
Leave out:
* profs_stats_by_year
    Overall ratings for professors based on year level of reviewer
    
* profs_stats_by_grade
    Rating Averages per reviewer's earned grade per review id

#### profs_df json

In [41]:
profs_df

                               Dept            Name  Reporting Evaluations
prof_id
2073     Chemistry and Biochemistry  Christina Abel                     32
728                    Architecture    Dick Zweifel                     16

In [42]:
p_df_json = profs_df.reset_index().to_json(orient='index') #don't drop index

In [43]:
pd.read_json(p_df_json).transpose()

                         Dept            Name Reporting Evaluations prof_id
0  Chemistry and Biochemistry  Christina Abel                    32    2073
1                Architecture    Dick Zweifel                    16     728

#### profs_stats json

In [44]:
profs_stats

   median   mean  std_dev  mode                      rating_type  prof_id
0       4  3.563    0.556     4                   Overall Rating     2073
1       4  3.594    0.551     4        Presents Material Clearly     2073
2       4  3.563    0.658     4  Recognizes Student Difficulties     2073
3       1  1.625    1.317     1                   Overall Rating      728
4       2  2.375    1.111     2        Presents Material Clearly      728
5       2  1.875    1.166     1  Recognizes Student Difficulties      728

In [45]:
p_stats_json = profs_stats.reset_index(drop=True).to_json(orient='index') # drop index
p_stats_json

'{"0":{"median":4,"mean":3.563,"std_dev":0.556,"mode":4,"rating_type":"Overall Rating","prof_id":2073},"1":{"median":4,"mean":3.594,"std_dev":0.551,"mode":4,"rating_type":"Presents Material Clearly","prof_id":2073},"2":{"median":4,"mean":3.563,"std_dev":0.658,"mode":4,"rating_type":"Recognizes Student Difficulties","prof_id":2073},"3":{"median":1,"mean":1.625,"std_dev":1.317,"mode":1,"rating_type":"Overall Rating","prof_id":728},"4":{"median":2,"mean":2.375,"std_dev":1.111,"mode":2,"rating_type":"Presents Material Clearly","prof_id":728},"5":{"median":2,"mean":1.875,"std_dev":1.166,"mode":1,"rating_type":"Recognizes Student Difficulties","prof_id":728}}'

In [46]:
pd.read_json(p_stats_json).transpose()

    mean median mode prof_id                      rating_type std_dev
0  3.563      4    4    2073                   Overall Rating   0.556
1  3.594      4    4    2073        Presents Material Clearly   0.551
2  3.563      4    4    2073  Recognizes Student Difficulties   0.658
3  1.625      1    1     728                   Overall Rating   1.317
4  2.375      2    2     728        Presents Material Clearly   1.111
5  1.875      2    1     728  Recognizes Student Difficulties   1.166

In [47]:
p_stats_by_grade_list_json = [df.to_json(orient='index') for df in profs_stats_by_grade_list]
p_stats_by_grade_list_json

['{"Overall Rating":{"A":3.769,"B":3.222,"C":3.75,"Credit":null,"D":3.0,"F":null,"N\\/A":3.0,"No Credit":null,"prof_id":2073},"Presents Material Clearly":{"A":3.769,"B":3.222,"C":3.75,"Credit":null,"D":3.0,"F":null,"N\\/A":4.0,"No Credit":null,"prof_id":2073},"Recognizes Student Difficulties":{"A":3.692,"B":3.222,"C":3.75,"Credit":null,"D":4.0,"F":null,"N\\/A":3.0,"No Credit":null,"prof_id":2073},"Reporting Evaluations":{"A":13.0,"B":9.0,"C":8.0,"Credit":null,"D":1.0,"F":null,"N\\/A":1.0,"No Credit":null,"prof_id":2073}}',
 '{"Overall Rating":{"A":null,"B":null,"C":null,"Credit":1.083,"D":null,"F":4.0,"N\\/A":3.0,"No Credit":null,"prof_id":728},"Presents Material Clearly":{"A":null,"B":null,"C":null,"Credit":1.917,"D":null,"F":4.0,"N\\/A":3.667,"No Credit":null,"prof_id":728},"Recognizes Student Difficulties":{"A":null,"B":null,"C":null,"Credit":1.333,"D":null,"F":4.0,"N\\/A":3.333,"No Credit":null,"prof_id":728},"Reporting Evaluations":{"A":null,"B":null,"C":null,"Credit":12.0,"D":null,"F":1.0,"N\\/A":3.0,"No Credit":null,"prof_id":728}}']

In [48]:
stats_by_grade = []
for df_json in p_stats_by_grade_list_json: 
    stats_by_grade.append(pd.read_json(df_json).transpose())
stats_by_grade[0].transpose()

,Overall Rating,Presents Material Clearly,Recognizes Student Difficulties,Reporting Evaluations
A,3.769,3.769,3.692,13
B,3.222,3.222,3.222,9
C,3.750,3.750,3.750,8
Credit,NaN,NaN,NaN,NaN
D,3.000,3.000,4.000,1
F,NaN,NaN,NaN,NaN
N/A,3.000,4.000,3.000,1
No Credit,NaN,NaN,NaN,NaN
prof_id,2073.000,2073.000,2073.000,2073

In [49]:
reviews_by_grade_json = reviews_by_grade.reset_index().to_json(orient='index')

In [50]:
pd.read_json(reviews_by_grade_json).transpose().set_index('review_id').head()

,Course,Grade,Overall Rating,Presents Material Clearly,Recognizes Student Difficulties,Reporting Evaluations,Review,Year,prof_id
review_id,,,,,,,,,
34359,CHEM 124,A,3.769,3.769,3.692,13,"To do well in Abel's class, the key is practic...",Freshman,2073
34176,CHEM 127,A,3.769,3.769,3.692,13,Great professor! I learned a lot in her class....,Freshman,2073
31660,CHEM 124,A,3.769,3.769,3.692,13,Dr. Abel is a great chem prof. I would recomme...,Freshman,2073
30100,CHEM 127,A,3.769,3.769,3.692,13,Abel's class is doable but very tedious. Her t...,Sophomore,2073
29539,CHEM 125,A,3.769,3.769,3.692,13,She is an excellent professor. She really pre...,Freshman,2073

In [51]:
def create_jsons(path, data):
    '''
    Uses json to save Data Frames to the path specified.
    
    Args: 
        path (string): where the data will be stored.
    
    Returns: 
        None.
    
    '''
    
    profs_df, profs_stats, profs_stats_by_grade_list, reviews_by_grade = data
    
    #don't drop index
    p_df_json = profs_df.reset_index().to_json(orient='index') 
    
    # drop index
    p_stats_json = profs_stats.reset_index(drop=True).to_json(orient='index') 
    
    
    p_stats_by_grade_list_json = \
        [df.to_json(orient='index') for df in profs_stats_by_grade_list]
    reviews_by_grade_json = reviews_by_grade.reset_index().to_json(orient='index')
    
    #create a json array
    json_array = \
        [p_df_json, p_stats_json, p_stats_by_grade_list_json, reviews_by_grade_json]
    
    
    with open(path, 'w') as outfile:
        json.dump(json_array, outfile)
        
create_jsons('/data/primitiveDataType/small_data.json', \
             [profs_df, profs_stats, profs_stats_by_grade_list, reviews_by_grade])

----------------------------------------------------------------------------------------------


# Let's Run the code for Every Professor!

# The code below consumes time and RAM.We must avoid overwhelming the polyratings site.In order to do this, there is a time stall between each call to scrape a professor details

Get links to all of the professors.

In [52]:
'''Get links to all the professors.
   Call parsing methods. 
'''
# Drop the first link to get links only linking to a professor page. 
professor_urls = get_professor_urls()[1:]

Drop professor pages that are incompatible with the code.

In [53]:
good_professor_urls = [p for p in professor_urls if '=1628' not in p]
good_professor_urls = [p for p in good_professor_urls if '=359' not in p]
good_professor_urls = [p for p in good_professor_urls if '=717' not in p]
good_professor_urls = [p for p in good_professor_urls if '=468' not in p]
good_professor_urls = [p for p in good_professor_urls if '=509' not in p]

print([p for p in good_professor_urls if '=717' in p])

[]

# TIME CONSUMING CODE
The following code takes a good hour to run because it gathers all the data for each professor on polyratings.

In [54]:
#This code takes forever to run.
professor_frames = get_all_professors_stats(good_professor_urls)

Professor:  2073

Professor:  2390

Professor:  2429

Professor:  1

Professor:  2

Professor:  746

Professor:  3

Professor:  1252

Professor:  2819

Professor:  1693

Professor:  2236

Professor:  1617

Professor:  4

Professor:  1007

Professor:  5

Professor:  3351

Professor:  4126

Professor:  6

Professor:  908

Professor:  1095

Professor:  4008

Professor:  4167

Professor:  2950

Professor:  1418

Professor:  2375

Professor:  990

Professor:  1748

Professor:  974

Professor:  778

Professor:  7

Professor:  2797

Professor:  3452

Professor:  3894

Professor:  2089

Professor:  8

Professor:  9

Professor:  10

Professor:  891

Professor:  11

Professor:  2820

Professor:  1403

Professor:  2374

Professor:  3035

Professor:  4050

Professor:  12

Professor:  13

Professor:  3500

Professor:  2712

Professor:  2739

Professor:  3126

Professor:  1991

Professor:  14

Professor:  1646

Professor:  4168

Professor:  2126

Professor:  964

Professor:  4172

Professor:  965

Professor:  852

Professor:  1035

Professor:  1736

Professor:  3608

Professor:  777

Professor:  15

Professor:  4140

Professor:  1534

Professor:  4112

Professor:  1457

Professor:  1158

Professor:  3442

Professor:  1114

Professor:  17

Professor:  18

Professor:  3538

Professor:  19

Professor:  3625

Professor:  888

Professor:  2944

Professor:  20

Professor:  1317

Professor:  4004

Professor:  21

Professor:  2904

Professor:  2146

Professor:  3068

Professor:  971

Professor:  2953

Professor:  2082

Professor:  2141

Professor:  22

Professor:  940

Professor:  999

Professor:  1387

Professor:  23

Professor:  24

Professor:  1551

Professor:  2997

Professor:  901

Professor:  4121

Professor:  25

Professor:  3052

Professor:  26

Professor:  1092

Professor:  4131

Professor:  4225

Professor:  4216

Professor:  2150

Professor:  1301

Professor:  27

Professor:  28

Professor:  1694

Professor:  3441

Professor:  29

Professor:  2742

Professor:  2340

Professor:  3986

Professor:  30

Professor:  2798

Professor:  4122

Professor:  3026

Professor:  2902

Professor:  4178

Professor:  988

Professor:  31

Professor:  32

Professor:  33

Professor:  3966

Professor:  34

Professor:  2012

Professor:  1427

Professor:  1419

Professor:  35

Professor:  36

Professor:  4156

Professor:  877

Professor:  1738

Professor:  37

Professor:  2993

Professor:  38

Professor:  4027

Professor:  1141

Professor:  2928

Professor:  2883

Professor:  1481

Professor:  1868

Professor:  39

Professor:  4044

Professor:  40

Professor:  3011

Professor:  3991

Professor:  788

Professor:  2916

Professor:  1430

Professor:  41

Professor:  4174

Professor:  2850

Professor:  1296

Professor:  42

Professor:  43

Professor:  3055

Professor:  1364

Professor:  44

Professor:  45

Professor:  47

Professor:  48

Professor:  49

Professor:  3967

Professor:  50

Professor:  3218

Professor:  2406

Professor:  51

Professor:  889

Professor:  1812

Professor:  1151

Professor:  52

Professor:  53

Professor:  2097

Professor:  3425

Professor:  1063

Professor:  3536

Professor:  54

Professor:  55

Professor:  1064

Professor:  2125

Professor:  1340

Professor:  1772

Professor:  2718

Professor:  1154

Professor:  56

Professor:  57

Professor:  2462

Professor:  58

Professor:  2782

Professor:  957

Professor:  59

Professor:  3019

Professor:  4015

Professor:  1269

Professor:  60

Professor:  61

Professor:  2694

Professor:  1044

Professor:  2711

Professor:  62

Professor:  4144

Professor:  63

Professor:  2867

Professor:  873

Professor:  858

Professor:  64

Professor:  4120

Professor:  1119

Professor:  65

Professor:  4221

Professor:  2360

Professor:  66

Professor:  1315

Professor:  3343

Professor:  2948

Professor:  67

Professor:  68

Professor:  2964

Professor:  800

Professor:  69

Professor:  3819

Professor:  913

Professor:  4092

Professor:  70

Professor:  836

Professor:  1710

Professor:  1242

Professor:  2907

Professor:  3329

Professor:  1070

Professor:  3943

Professor:  1330

Professor:  3993

Professor:  71

Professor:  4183

Professor:  72

Professor:  73

Professor:  1960

Professor:  74

Professor:  76

Professor:  77

Professor:  2910

Professor:  75

Professor:  1150

Professor:  79

Professor:  78

Professor:  758

Professor:  3947

Professor:  80

Professor:  3015

Professor:  81

Professor:  1776

Professor:  82

Professor:  2475

Professor:  2974

Professor:  1591

Professor:  83

Professor:  1556

Professor:  2116

Professor:  1461

Professor:  84

Professor:  796

Professor:  1225

Professor:  3913

Professor:  3990

Professor:  85

Professor:  3299

Professor:  3964

Professor:  3903

Professor:  1490

Professor:  2454

Professor:  3989

Professor:  86

Professor:  2515

Professor:  1541

Professor:  87

Professor:  2817

Professor:  88

Professor:  3444

Professor:  1181

Professor:  2818

Professor:  1742

Professor:  2617

Professor:  2682

Professor:  89

Professor:  2963

Professor:  2922

Professor:  2404

Professor:  1745

Professor:  3362

Professor:  3451

Professor:  4208

Professor:  3066

Professor:  2889

Professor:  90

Professor:  4170

Professor:  2831

Professor:  2728

Professor:  747

Professor:  1062

Professor:  4185

Professor:  91

Professor:  3939

Professor:  92

Professor:  93

Professor:  94

Professor:  3985

Professor:  2135

Professor:  1624

Professor:  1263

Professor:  2759

Professor:  3898

Professor:  95

Professor:  2720

Professor:  96

Professor:  1278

Professor:  97

Professor:  98

Professor:  3979

Professor:  99

Professor:  100

Professor:  1236

Professor:  3496

Professor:  101

Professor:  1822

Professor:  2459

Professor:  1359

Professor:  102

Professor:  1341

Professor:  2227

Professor:  2367

Professor:  2557

Professor:  925

Professor:  3959

Professor:  2653

Professor:  103

Professor:  1176

Professor:  2191

Professor:  2777

Professor:  3090

Professor:  3515

Professor:  104

Professor:  105

Professor:  106

Professor:  4035

Professor:  4034

Professor:  1220

Professor:  1540

Professor:  1323

Professor:  107

Professor:  108

Professor:  1408

Professor:  1921

Professor:  2658

Professor:  2987

Professor:  109

Professor:  813

Professor:  110

Professor:  111

Professor:  2250

Professor:  4222

Professor:  112

Professor:  1896

Professor:  114

Professor:  113

Professor:  1147

Professor:  1379

Professor:  1774

Professor:  1347

Professor:  2138

Professor:  115

Professor:  2155

Professor:  1810

Professor:  1021

Professor:  116

Professor:  2854

Professor:  1570

Professor:  4047

Professor:  969

Professor:  2348

Professor:  2417

Professor:  117

Professor:  879

Professor:  118

Professor:  1860

Professor:  1316

Professor:  1747

Professor:  1193

Professor:  2870

Professor:  828

Professor:  119

Professor:  1640

Professor:  3928

Professor:  120

Professor:  1104

Professor:  121

Professor:  122

Professor:  2859

Professor:  123

Professor:  4176

Professor:  124

Professor:  869

Professor:  4101

Professor:  4180

Professor:  125

Professor:  126

Professor:  127

Professor:  2527

Professor:  2412

Professor:  128

Professor:  1194

Professor:  129

Professor:  1047

Professor:  130

Professor:  131

Professor:  931

Professor:  1767

Professor:  132

Professor:  1054

Professor:  2734

Professor:  2750

Professor:  2054

Professor:  3054

Professor:  1172

Professor:  133

Professor:  134

Professor:  2885

Professor:  2144

Professor:  1878

Professor:  3048

Professor:  135

Professor:  950

Professor:  1005

Professor:  1717

Professor:  1471

Professor:  966

Professor:  136

Professor:  1011

Professor:  2049

Professor:  137

Professor:  1739

Professor:  139

Professor:  955

Professor:  140

Professor:  141

Professor:  1508

Professor:  907

Professor:  2796

Professor:  2801

Professor:  142

Professor:  1122

Professor:  143

Professor:  4032

Professor:  3322

Professor:  4141

Professor:  1177

Professor:  144

Professor:  145

Professor:  146

Professor:  147

Professor:  148

Professor:  2059

Professor:  1013

Professor:  1544

Professor:  2812

Professor:  2132

Professor:  149

Professor:  1155

Professor:  3917

Professor:  1293

Professor:  150

Professor:  3607

Professor:  3968

Professor:  151

Professor:  865

Professor:  152

Professor:  982

Professor:  1470

Professor:  924

Professor:  1249

Professor:  846

Professor:  1138

Professor:  3211

Professor:  3719

Professor:  153

Professor:  4143

Professor:  2368

Professor:  2371

Professor:  4028

Professor:  2152

Professor:  4151

Professor:  154

Professor:  856

Professor:  1421

Professor:  155

Professor:  1284

Professor:  1462

Professor:  1332

Professor:  1635

Professor:  156

Professor:  157

Professor:  1358

Professor:  1778

Professor:  1561

Professor:  158

Professor:  159

Professor:  160

Professor:  4137

Professor:  1219

Professor:  161

Professor:  4048

Professor:  3388

Professor:  1598

Professor:  3946

Professor:  1487

Professor:  2946

Professor:  162

Professor:  163

Professor:  3418

Professor:  164

Professor:  165

Professor:  2827

Professor:  2792

Professor:  166

Professor:  4057

Professor:  1370

Professor:  1111

Professor:  2257

Professor:  167

Professor:  3908

Professor:  1362

Professor:  2067

Professor:  3084

Professor:  2747

Professor:  168

Professor:  1075

Professor:  169

Professor:  170

Professor:  4058

Professor:  2055

Professor:  1257

Professor:  986

Professor:  171

Professor:  172

Professor:  1719

Professor:  1320

Professor:  2635

Professor:  2725

Professor:  173

Professor:  941

Professor:  1484

Professor:  3114

Professor:  174

Professor:  4003

Professor:  2770

Professor:  2221

Professor:  976

Professor:  2758

Professor:  1852

Professor:  2843

Professor:  2835

Professor:  175

Professor:  3110

Professor:  176

Professor:  739

Professor:  916

Professor:  177

Professor:  4163

Professor:  178

Professor:  179

Professor:  180

Professor:  4201

Professor:  2133

Professor:  1346

Professor:  3953

Professor:  3969

Professor:  2321

Professor:  181

Professor:  1582

Professor:  3028

Professor:  3914

Professor:  3978

Professor:  2842

Professor:  182

Professor:  183

Professor:  2722

Professor:  3077

Professor:  2153

Professor:  1382

Professor:  3044

Professor:  184

Professor:  4199

Professor:  1363

Professor:  2768

Professor:  1012

Professor:  1335

Professor:  3010

Professor:  185

Professor:  2445

Professor:  2598

Professor:  4165

Professor:  1162

Professor:  1961

Professor:  872

Professor:  186

Professor:  187

Professor:  4124

Professor:  188

Professor:  189

Professor:  3952

Professor:  2310

Professor:  190

Professor:  3619

Professor:  3365

Professor:  757

Professor:  3440

Professor:  191

Professor:  1096

Professor:  3376

Professor:  193

Professor:  2888

Professor:  3121

Professor:  2450

Professor:  2387

Professor:  3378

Professor:  4065

Professor:  4074

Professor:  2107

Professor:  3408

Professor:  194

Professor:  1724

Professor:  195

Professor:  1597

Professor:  782

Professor:  196

Professor:  1050

Professor:  2289

Professor:  2187

Professor:  197

Professor:  2223

Professor:  1325

Professor:  2432

Professor:  198

Professor:  3929

Professor:  1509

Professor:  1378

Professor:  1377

Professor:  199

Professor:  201

Professor:  3368

Professor:  3369

Professor:  202

Professor:  1006

Professor:  833

Professor:  1843

Professor:  2607

Professor:  1807

Professor:  203

Professor:  204

Professor:  1782

Professor:  205

Professor:  3061

Professor:  3308

Professor:  2752

Professor:  206

Professor:  1777

Professor:  1831

Professor:  207

Professor:  1106

Professor:  208

Professor:  209

Professor:  4160

Professor:  3353

Professor:  1828

Professor:  765

Professor:  210

Professor:  842

Professor:  3688

Professor:  211

Professor:  2075

Professor:  212

Professor:  213

Professor:  2544

Professor:  214

Professor:  216

Professor:  215

Professor:  2091

Professor:  217

Professor:  896

Professor:  1795

Professor:  1689

Professor:  3902

Professor:  4060

Professor:  218

Professor:  1020

Professor:  219

Professor:  3911

Professor:  2929

Professor:  791

Professor:  220

Professor:  3162

Professor:  221

Professor:  1535

Professor:  794

Professor:  222

Professor:  4147

Professor:  2858

Professor:  223

Professor:  224

Professor:  225

Professor:  803

Professor:  1051

Professor:  2318

Professor:  763

Professor:  1089

Professor:  1906

Professor:  1904

Professor:  1165

Professor:  1928

Professor:  226

Professor:  787

Professor:  2351

Professor:  2419

Professor:  1019

Professor:  200

Professor:  2159

Professor:  933

Professor:  2802

Professor:  2978

Professor:  3018

Professor:  1033

Professor:  1201

Professor:  227

Professor:  1871

Professor:  228

Professor:  229

Professor:  2828

Professor:  4049

Professor:  3529

Professor:  2927

Professor:  946

Professor:  1426

Professor:  3934

Professor:  1302

Professor:  503

Professor:  3386

Professor:  2337

Professor:  1931

Professor:  230

Professor:  231

Professor:  3750

Professor:  232

Professor:  1763

Professor:  1785

Professor:  1014

Professor:  233

Professor:  234

Professor:  235

Professor:  236

Professor:  3996

Professor:  871

Professor:  237

Professor:  238

Professor:  240

Professor:  1398

Professor:  241

Professor:  242

Professor:  960

Professor:  1393

Professor:  243

Professor:  1412

Professor:  244

Professor:  1669

Professor:  1329

Professor:  1495

Professor:  3025

Professor:  3034

Professor:  1216

Professor:  245

Professor:  1667

Professor:  246

Professor:  247

Professor:  1732

Professor:  3468

Professor:  1127

Professor:  2610

Professor:  2147

Professor:  998

Professor:  248

Professor:  249

Professor:  1659

Professor:  2683

Professor:  250

Professor:  1496

Professor:  3511

Professor:  1537

Professor:  1605

Professor:  4038

Professor:  4011

Professor:  1429

Professor:  4227

Professor:  251

Professor:  2314

Professor:  2064

Professor:  252

Professor:  2945

Professor:  4207

Professor:  3460

Professor:  253

Professor:  1800

Professor:  818

Professor:  254

Professor:  802

Professor:  1260

Professor:  909

Professor:  1130

Professor:  255

Professor:  1322

Professor:  256

Professor:  2094

Professor:  2078

Professor:  1839

Professor:  1498

Professor:  1876

Professor:  4171

Professor:  4113

Professor:  257

Professor:  4204

Professor:  258

Professor:  910

Professor:  1314

Professor:  2619

Professor:  2721

Professor:  2662

Professor:  1737

Professor:  1326

Professor:  2932

Professor:  827

Professor:  1734

Professor:  983

Professor:  1112

Professor:  259

Professor:  3409

Professor:  2803

Professor:  1696

Professor:  260

Professor:  3039

Professor:  261

Professor:  1450

Professor:  2134

Professor:  262

Professor:  1907

Professor:  3071

Professor:  263

Professor:  3128

Professor:  1626

Professor:  264

Professor:  2924

Professor:  3884

Professor:  2062

Professor:  1762

Professor:  1639

Professor:  265

Professor:  267

Professor:  268

Professor:  269

Professor:  270

Professor:  271

Professor:  272

Professor:  1031

Professor:  4094

Professor:  3030

Professor:  273

Professor:  274

Professor:  1602

Professor:  1410

Professor:  3067

Professor:  1422

Professor:  2123

Professor:  4006

Professor:  1797

Professor:  1239

Professor:  275

Professor:  276

Professor:  1149

Professor:  3944

Professor:  2804

Professor:  277

Professor:  2332

Professor:  278

Professor:  4150

Professor:  279

Professor:  3950

Professor:  1381

Professor:  280

Professor:  2881

Professor:  1673

Professor:  2869

Professor:  923

Professor:  1339

Professor:  4072

Professor:  1367

Professor:  1142

Professor:  282

Professor:  2364

Professor:  283

Professor:  1486

Professor:  1351

Professor:  1232

Professor:  895

Professor:  2166

Professor:  943

Professor:  4020

Professor:  2736

Professor:  2762

Professor:  2791

Professor:  2786

Professor:  886

Professor:  2934

Professor:  2118

Professor:  284

Professor:  285

Professor:  1585

Professor:  1723

Professor:  1459

Professor:  286

Professor:  1607

Professor:  3717

Professor:  287

Professor:  288

Professor:  289

Professor:  1191

Professor:  2998

Professor:  290

Professor:  291

Professor:  1665

Professor:  1109

Professor:  2346

Professor:  292

Professor:  2769

Professor:  4067

Professor:  293

Professor:  294

Professor:  3710

Professor:  1791

Professor:  930

Professor:  2723

Professor:  1108

Professor:  295

Professor:  2973

Professor:  2485

Professor:  1174

Professor:  296

Professor:  1342

Professor:  2729

Professor:  1365

Professor:  297

Professor:  2936

Professor:  298

Professor:  1525

Professor:  3111

Professor:  2951

Professor:  299

Professor:  300

Professor:  301

Professor:  2892

Professor:  830

Professor:  302

Professor:  303

Professor:  2158

Professor:  762

Professor:  3003

Professor:  2601

Professor:  2111

Professor:  1243

Professor:  3492

Professor:  304

Professor:  1873

Professor:  1060

Professor:  2620

Professor:  305

Professor:  1276

Professor:  3083

Professor:  306

Professor:  4136

Professor:  2131

Professor:  307

Professor:  1857

Professor:  2053

Professor:  308

Professor:  309

Professor:  4123

Professor:  1389

Professor:  310

Professor:  3550

Professor:  311

Professor:  2358

Professor:  3024

Professor:  745

Professor:  1533

Professor:  3733

Professor:  312

Professor:  4149

Professor:  2313

Professor:  2316

Professor:  2436

Professor:  2701

Professor:  3350

Professor:  313

Professor:  2335

Professor:  314

Professor:  1308

Professor:  2807

Professor:  2816

Professor:  3674

Professor:  2087

Professor:  2809

Professor:  315

Professor:  1611

Professor:  1170

Professor:  2749

Professor:  1156

Professor:  1305

Professor:  4021

Professor:  316

Professor:  317

Professor:  1373

Professor:  754

Professor:  1511

Professor:  1592

Professor:  2379

Professor:  2394

Professor:  815

Professor:  4091

Professor:  755

Professor:  3149

Professor:  319

Professor:  318

Professor:  320

Professor:  3254

Professor:  2452

Professor:  2440

Professor:  1255

Professor:  321

Professor:  4129

Professor:  3889

Professor:  322

Professor:  750

Professor:  2756

Professor:  1152

Professor:  3342

Professor:  325

Professor:  324

Professor:  323

Professor:  3017

Professor:  2129

Professor:  1811

Professor:  1657

Professor:  326

Professor:  1086

Professor:  3963

Professor:  2195

Professor:  327

Professor:  328

Professor:  1121

Professor:  1753

Professor:  2872

Professor:  867

Professor:  1168

Professor:  2930

Professor:  329

Professor:  330

Professor:  820

Professor:  1103

Professor:  1261

Professor:  331

Professor:  2035

Professor:  4026

Professor:  332

Professor:  4061

Professor:  4203

Professor:  3096

Professor:  1287

Professor:  333

Professor:  1414

Professor:  334

Professor:  4152

Professor:  335

Professor:  2689

Professor:  1010

Professor:  336

Professor:  337

Professor:  2979

Professor:  898

Professor:  932

Professor:  3909

Professor:  2366

Professor:  1265

Professor:  934

Professor:  338

Professor:  2019

Professor:  1559

Professor:  1078

Professor:  339

Professor:  4215

Professor:  1910

Professor:  1682

Professor:  2795

Professor:  2949

Professor:  1304

Professor:  1024

Professor:  1038

Professor:  3079

Professor:  2370

Professor:  340

Professor:  341

Professor:  3101

Professor:  2906

Professor:  3394

Professor:  2552

Professor:  2027

Professor:  2345

Professor:  2781

Professor:  342

Professor:  2569

Professor:  343

Professor:  344

Professor:  840

Professor:  345

Professor:  2826

Professor:  2861

Professor:  2137

Professor:  956

Professor:  899

Professor:  1932

Professor:  2913

Professor:  841


In [57]:
assert len(professor_frames) == 2416

## Inspect the Dataframes

In [58]:
professors, p_stats, p_stats_by_grade, p_stats_by_year, p_stats_by_grade_list = \
    merge_professors(professor_frames)

                               Dept            Name  Reporting Evaluations
prof_id
2073     Chemistry and Biochemistry  Christina Abel                     32
   median   mean  std_dev  mode                      rating_type  prof_id
0       4  3.563    0.556     4                   Overall Rating     2073
1       4  3.594    0.551     4        Presents Material Clearly     2073
2       4  3.563    0.658     4  Recognizes Student Difficulties     2073
                                      A      B     C Credit  D     F  N/A  \
Overall Rating                    3.769  3.222  3.75   None  3  None    3
Presents Material Clearly         3.769  3.222  3.75   None  3  None    4
Recognizes Student Difficulties   3.692  3.222  3.75   None  4  None    3
Reporting Evaluations            13.000  9.000  8.00   None  1  None    1

                                No Credit  prof_id
Overall Rating                       None     2073
Presents Material Clearly            None     2073
Recognizes Student Difficulties      None     2073
Reporting Evaluations                None     2073
                                5th Year Senior  Freshman Graduate Student  \
Overall Rating                             None     3.500             None
Presents Material Clearly                  None     3.714             None
Recognizes Student Difficulties            None     3.571             None
Reporting Evaluations                      None    14.000             None

                                 Junior  Senior  Sophomore  prof_id
Overall Rating                    4.000   3.333      3.583     2073
Presents Material Clearly         3.667   3.333      3.500     2073
Recognizes Student Difficulties   4.000   3.667      3.417     2073
Reporting Evaluations             3.000   3.000     12.000     2073

In [59]:
professors.tail()

,Dept,Name,Reporting Evaluations
prof_id,,,
726,Environmental Horticulture Science,Michael Zohns,8
3027,Philosophy,David Zoller,9
727,Social Sciences,Maliha Zulfacar,87
1758,Chemistry and Biochemistry,Marta Zumwalt,13
728,Architecture,Dick Zweifel,16

In [60]:
p_stats.tail(10)

      median   mean  std_dev  mode                      rating_type  prof_id
5255       0  2.778    1.133     3  Recognizes Student Difficulties     3027
5256       0  1.989    1.615     4                   Overall Rating      727
5257       0  2.023    1.454     4        Presents Material Clearly      727
5258       0  1.839    1.538     0  Recognizes Student Difficulties      727
5259       0  2.769    1.367     4                   Overall Rating     1758
5260       0  2.923    1.385     4        Presents Material Clearly     1758
5261       0  2.462    1.278     2  Recognizes Student Difficulties     1758
5262       1  1.625    1.317     1                   Overall Rating      728
5263       2  2.375    1.111     2        Presents Material Clearly      728
5264       2  1.875    1.166     1  Recognizes Student Difficulties      728

In [61]:
p_stats_by_grade_list[-3]

,A,B,C,Credit,D,F,N/A,No Credit,prof_id
Overall Rating,3.125,1.939,0.889,3.0,0.0,1.0,1.286,None,727
Presents Material Clearly,2.958,2.000,1.333,2.5,0.0,1.5,1.357,None,727
Recognizes Student Difficulties,3.000,1.697,1.000,2.5,0.5,1.0,1.071,None,727
Reporting Evaluations,24.000,33.000,9.000,2.0,2.0,2.0,14.000,None,727

In [62]:
#THis takes a long, long time to run. 
#Prints out the professor ID of the professor that it's processing.
professor_reviews = get_all_profs_reviews(good_professor_urls)

Professor Id:  2073
Professor Id:  2390
Professor Id:  2429
Professor Id:  1
Professor Id:  2
Professor Id:  746
Professor Id:  3
Professor Id:  1252
Professor Id:  2819
Professor Id:  1693
Professor Id:  2236
Professor Id:  1617
Professor Id:  4
Professor Id:  1007
Professor Id:  5
Professor Id:  3351
Professor Id:  4126
Professor Id:  6
Professor Id:  908
Professor Id:  1095
Professor Id:  4008
Professor Id:  4167
Professor Id:  2950
Professor Id:  1418
Professor Id:  2375
Professor Id:  990
Professor Id:  1748
Professor Id:  974
Professor Id:  778
Professor Id:  7
Professor Id:  2797
Professor Id:  3452
Professor Id:  3894
Professor Id:  2089
Professor Id:  8
Professor Id:  9
Professor Id:  10
Professor Id:  891
Professor Id:  11
Professor Id:  2820
Professor Id:  1403
Professor Id:  2374
Professor Id:  3035
Professor Id:  4050
Professor Id:  12
Professor Id:  13
Professor Id:  3500
Professor Id:  2712
Professor Id:  2739
Professor Id:  3126
Professor Id:  1991
Professor Id:  14
Professor Id:  1646
Professor Id:  4168
Professor Id:  2126
Professor Id:  964
Professor Id:  4172
Professor Id:  965
Professor Id:  852
Professor Id:  1035
Professor Id:  1736
Professor Id:  3608
Professor Id:  777
Professor Id:  15
Professor Id:  4140
Professor Id:  1534
Professor Id:  4112
Professor Id:  1457
Professor Id:  1158
Professor Id:  3442
Professor Id:  1114
Professor Id:  17
Professor Id:  18
Professor Id:  3538
Professor Id:  19
Professor Id:  3625
Professor Id:  888
Professor Id:  2944
Professor Id:  20
Professor Id:  1317
Professor Id:  4004
Professor Id:  21
Professor Id:  2904
Professor Id:  2146
Professor Id:  3068
Professor Id:  971
Professor Id:  2953
Professor Id:  2082
Professor Id:  2141
Professor Id:  22
Professor Id:  940
Professor Id:  999
Professor Id:  1387
Professor Id:  23
Professor Id:  24
Professor Id:  1551
Professor Id:  2997
Professor Id:  901
Professor Id:  4121
Professor Id:  25
Professor Id:  3052
Professor Id:  26
Professor Id:  1092
Professor Id:  4131
Professor Id:  4225
Professor Id:  4216
Professor Id:  2150
Professor Id:  1301
Professor Id:  27
Professor Id:  28
Professor Id:  1694
Professor Id:  3441
Professor Id:  29
Professor Id:  2742
Professor Id:  2340
Professor Id:  3986
Professor Id:  30
Professor Id:  2798
Professor Id:  4122
Professor Id:  3026
Professor Id:  2902
Professor Id:  4178
Professor Id:  988
Professor Id:  31
Professor Id:  32
Professor Id:  33
Professor Id:  3966
Professor Id:  34
Professor Id:  2012
Professor Id:  1427
Professor Id:  1419
Professor Id:  35
Professor Id:  36
Professor Id:  4156
Professor Id:  877
Professor Id:  1738
Professor Id:  37
Professor Id:  2993
Professor Id:  38
Professor Id:  4027
Professor Id:  1141
Professor Id:  2928
Professor Id:  2883
Professor Id:  1481
Professor Id:  1868
Professor Id:  39
Professor Id:  4044
Professor Id:  40
Professor Id:  3011
Professor Id:  3991
Professor Id:  788
Professor Id:  2916
Professor Id:  1430
Professor Id:  41
Professor Id:  4174
Professor Id:  2850
Professor Id:  1296
Professor Id:  42
Professor Id:  43
Professor Id:  3055
Professor Id:  1364
Professor Id:  44
Professor Id:  45
Professor Id:  47
Professor Id:  48
Professor Id:  49
Professor Id:  3967
Professor Id:  50
Professor Id:  3218
Professor Id:  2406
Professor Id:  51
Professor Id:  889
Professor Id:  1812
Professor Id:  1151
Professor Id:  52
Professor Id:  53
Professor Id:  2097
Professor Id:  3425
Professor Id:  1063
Professor Id:  3536
Professor Id:  54
Professor Id:  55
Professor Id:  1064
Professor Id:  2125
Professor Id:  1340
Professor Id:  1772
Professor Id:  2718
Professor Id:  1154
Professor Id:  56
Professor Id:  57
Professor Id:  2462
Professor Id:  58
Professor Id:  2782
Professor Id:  957
Professor Id:  59
Professor Id:  3019
Professor Id:  4015
Professor Id:  1269
Professor Id:  60
Professor Id:  61
Professor Id:  2694
Professor Id:  1044
Professor Id:  2711
Professor Id:  62
Professor Id:  4144
Professor Id:  63
Professor Id:  2867
Professor Id:  873
Professor Id:  858
Professor Id:  64
Professor Id:  4120
Professor Id:  1119
Professor Id:  65
Professor Id:  4221
Professor Id:  2360
Professor Id:  66
Professor Id:  1315
Professor Id:  3343
Professor Id:  2948
Professor Id:  67
Professor Id:  68
Professor Id:  2964
Professor Id:  800
Professor Id:  69
Professor Id:  3819
Professor Id:  913
Professor Id:  4092
Professor Id:  70
Professor Id:  836
Professor Id:  1710
Professor Id:  1242
Professor Id:  2907
Professor Id:  3329
Professor Id:  1070
Professor Id:  3943
Professor Id:  1330
Professor Id:  3993
Professor Id:  71
Professor Id:  4183
Professor Id:  72
Professor Id:  73
Professor Id:  1960
Professor Id:  74
Professor Id:  76
Professor Id:  77
Professor Id:  2910
Professor Id:  75
Professor Id:  1150
Professor Id:  79
Professor Id:  78
Professor Id:  758
Professor Id:  3947
Professor Id:  80
Professor Id:  3015
Professor Id:  81
Professor Id:  1776
Professor Id:  82
Professor Id:  2475
Professor Id:  2974
Professor Id:  1591
Professor Id:  83
Professor Id:  1556
Professor Id:  2116
Professor Id:  1461
Professor Id:  84
Professor Id:  796
Professor Id:  1225
Professor Id:  3913
Professor Id:  3990
Professor Id:  85
Professor Id:  3299
Professor Id:  3964
Professor Id:  3903
Professor Id:  1490
Professor Id:  2454
Professor Id:  3989
Professor Id:  86
Professor Id:  2515
Professor Id:  1541
Professor Id:  87
Professor Id:  2817
Professor Id:  88
Professor Id:  3444
Professor Id:  1181
Professor Id:  2818
Professor Id:  1742
Professor Id:  2617
Professor Id:  2682
Professor Id:  89
Professor Id:  2963
Professor Id:  2922
Professor Id:  2404
Professor Id:  1745
Professor Id:  3362
Professor Id:  3451
Professor Id:  4208
Professor Id:  3066
Professor Id:  2889
Professor Id:  90
Professor Id:  4170
Professor Id:  2831
Professor Id:  2728
Professor Id:  747
Professor Id:  1062
Professor Id:  4185
Professor Id:  91
Professor Id:  3939
Professor Id:  92
Professor Id:  93
Professor Id:  94
Professor Id:  3985
Professor Id:  2135
Professor Id:  1624
Professor Id:  1263
Professor Id:  2759
Professor Id:  3898
Professor Id:  95
Professor Id:  2720
Professor Id:  96
Professor Id:  1278
Professor Id:  97
Professor Id:  98
Professor Id:  3979
Professor Id:  99
Professor Id:  100
Professor Id:  1236
Professor Id:  3496
Professor Id:  101
Professor Id:  1822
Professor Id:  2459
Professor Id:  1359
Professor Id:  102
Professor Id:  1341
Professor Id:  2227
Professor Id:  2367
Professor Id:  2557
Professor Id:  925
Professor Id:  3959
Professor Id:  2653
Professor Id:  103
Professor Id:  1176
Professor Id:  2191
Professor Id:  2777
Professor Id:  3090
Professor Id:  3515
Professor Id:  104
Professor Id:  105
Professor Id:  106
Professor Id:  4035
Professor Id:  4034
Professor Id:  1220
Professor Id:  1540
Professor Id:  1323
Professor Id:  107
Professor Id:  108
Professor Id:  1408
Professor Id:  1921
Professor Id:  2658
Professor Id:  2987
Professor Id:  109
Professor Id:  813
Professor Id:  110
Professor Id:  111
Professor Id:  2250
Professor Id:  4222
Professor Id:  112
Professor Id:  1896
Professor Id:  114
Professor Id:  113
Professor Id:  1147
Professor Id:  1379
Professor Id:  1774
Professor Id:  1347
Professor Id:  2138
Professor Id:  115
Professor Id:  2155
Professor Id:  1810
Professor Id:  1021
Professor Id:  116
Professor Id:  2854
Professor Id:  1570
Professor Id:  4047
Professor Id:  969
Professor Id:  2348
Professor Id:  2417
Professor Id:  117
Professor Id:  879
Professor Id:  118
Professor Id:  1860
Professor Id:  1316
Professor Id:  1747
Professor Id:  1193
Professor Id:  2870
Professor Id:  828
Professor Id:  119
Professor Id:  1640
Professor Id:  3928
Professor Id:  120
Professor Id:  1104
Professor Id:  121
Professor Id:  122
Professor Id:  2859
Professor Id:  123
Professor Id:  4176
Professor Id:  124
Professor Id:  869
Professor Id:  4101
Professor Id:  4180
Professor Id:  125
Professor Id:  126
Professor Id:  127
Professor Id:  2527
Professor Id:  2412
Professor Id:  128
Professor Id:  1194
Professor Id:  129
Professor Id:  1047
Professor Id:  130
Professor Id:  131
Professor Id:  931
Professor Id:  1767
Professor Id:  132
Professor Id:  1054
Professor Id:  2734
Professor Id:  2750
Professor Id:  2054
Professor Id:  3054
Professor Id:  1172
Professor Id:  133
Professor Id:  134
Professor Id:  2885
Professor Id:  2144
Professor Id:  1878
Professor Id:  3048
Professor Id:  135
Professor Id:  950
Professor Id:  1005
Professor Id:  1717
Professor Id:  1471
Professor Id:  966
Professor Id:  136
Professor Id:  1011
Professor Id:  2049
Professor Id:  137
Professor Id:  1739
Professor Id:  139
Professor Id:  955
Professor Id:  140
Professor Id:  141
Professor Id:  1508
Professor Id:  907
Professor Id:  2796
Professor Id:  2801
Professor Id:  142
Professor Id:  1122
Professor Id:  143
Professor Id:  4032
Professor Id:  3322
Professor Id:  4141
Professor Id:  1177
Professor Id:  144
Professor Id:  145
Professor Id:  146
Professor Id:  147
Professor Id:  148
Professor Id:  2059
Professor Id:  1013
Professor Id:  1544
Professor Id:  2812
Professor Id:  2132
Professor Id:  149
Professor Id:  1155
Professor Id:  3917
Professor Id:  1293
Professor Id:  150
Professor Id:  3607
Professor Id:  3968
Professor Id:  151
Professor Id:  865
Professor Id:  152
Professor Id:  982
Professor Id:  1470
Professor Id:  924
Professor Id:  1249
Professor Id:  846
Professor Id:  1138
Professor Id:  3211
Professor Id:  3719
Professor Id:  153
Professor Id:  4143
Professor Id:  2368
Professor Id:  2371
Professor Id:  4028
Professor Id:  2152
Professor Id:  4151
Professor Id:  154
Professor Id:  856
Professor Id:  1421
Professor Id:  155
Professor Id:  1284
Professor Id:  1462
Professor Id:  1332
Professor Id:  1635
Professor Id:  156
Professor Id:  157
Professor Id:  1358
Professor Id:  1778
Professor Id:  1561
Professor Id:  158
Professor Id:  159
Professor Id:  160
Professor Id:  4137
Professor Id:  1219
Professor Id:  161
Professor Id:  4048
Professor Id:  3388
Professor Id:  1598
Professor Id:  3946
Professor Id:  1487
Professor Id:  2946
Professor Id:  162
Professor Id:  163
Professor Id:  3418
Professor Id:  164
Professor Id:  165
Professor Id:  2827
Professor Id:  2792
Professor Id:  166
Professor Id:  4057
Professor Id:  1370
Professor Id:  1111
Professor Id:  2257
Professor Id:  167
Professor Id:  3908
Professor Id:  1362
Professor Id:  2067
Professor Id:  3084
Professor Id:  2747
Professor Id:  168
Professor Id:  1075
Professor Id:  169
Professor Id:  170
Professor Id:  4058
Professor Id:  2055
Professor Id:  1257
Professor Id:  986
Professor Id:  171
Professor Id:  172
Professor Id:  1719
Professor Id:  1320
Professor Id:  2635
Professor Id:  2725
Professor Id:  173
Professor Id:  941
Professor Id:  1484
Professor Id:  3114
Professor Id:  174
Professor Id:  4003
Professor Id:  2770
Professor Id:  2221
Professor Id:  976
Professor Id:  2758
Professor Id:  1852
Professor Id:  2843
Professor Id:  2835
Professor Id:  175
Professor Id:  3110
Professor Id:  176
Professor Id:  739
Professor Id:  916
Professor Id:  177
Professor Id:  4163
Professor Id:  178
Professor Id:  179
Professor Id:  180
Professor Id:  4201
Professor Id:  2133
Professor Id:  1346
Professor Id:  3953
Professor Id:  3969
Professor Id:  2321
Professor Id:  181
Professor Id:  1582
Professor Id:  3028
Professor Id:  3914
Professor Id:  3978
Professor Id:  2842
Professor Id:  182
Professor Id:  183
Professor Id:  2722
Professor Id:  3077
Professor Id:  2153
Professor Id:  1382
Professor Id:  3044
Professor Id:  184
Professor Id:  4199
Professor Id:  1363
Professor Id:  2768
Professor Id:  1012
Professor Id:  1335
Professor Id:  3010
Professor Id:  185
Professor Id:  2445
Professor Id:  2598
Professor Id:  4165
Professor Id:  1162
Professor Id:  1961
Professor Id:  872
Professor Id:  186
Professor Id:  187
Professor Id:  4124
Professor Id:  188
Professor Id:  189
Professor Id:  3952
Professor Id:  2310
Professor Id:  190
Professor Id:  3619
Professor Id:  3365
Professor Id:  757
Professor Id:  3440
Professor Id:  191
Professor Id:  1096
Professor Id:  3376
Professor Id:  193
Professor Id:  2888
Professor Id:  3121
Professor Id:  2450
Professor Id:  2387
Professor Id:  3378
Professor Id:  4065
Professor Id:  4074
Professor Id:  2107
Professor Id:  3408
Professor Id:  194
Professor Id:  1724
Professor Id:  195
Professor Id:  1597
Professor Id:  782
Professor Id:  196
Professor Id:  1050
Professor Id:  2289
Professor Id:  2187
Professor Id:  197
Professor Id:  2223
Professor Id:  1325
Professor Id:  2432
Professor Id:  198
Professor Id:  3929
Professor Id:  1509
Professor Id:  1378
Professor Id:  1377
Professor Id:  199
Professor Id:  201
Professor Id:  3368
Professor Id:  3369
Professor Id:  202
Professor Id:  1006
Professor Id:  833
Professor Id:  1843
Professor Id:  2607
Professor Id:  1807
Professor Id:  203
Professor Id:  204
Professor Id:  1782
Professor Id:  205
Professor Id:  3061
Professor Id:  3308
Professor Id:  2752
Professor Id:  206
Professor Id:  1777
Professor Id:  1831
Professor Id:  207
Professor Id:  1106
Professor Id:  208
Professor Id:  209
Professor Id:  4160
Professor Id:  3353
Professor Id:  1828
Professor Id:  765
Professor Id:  210
Professor Id:  842
Professor Id:  3688
Professor Id:  211
Professor Id:  2075
Professor Id:  212
Professor Id:  213
Professor Id:  2544
Professor Id:  214
Professor Id:  216
Professor Id:  215
Professor Id:  2091
Professor Id:  217
Professor Id:  896
Professor Id:  1795
Professor Id:  1689
Professor Id:  3902
Professor Id:  4060
Professor Id:  218
Professor Id:  1020
Professor Id:  219
Professor Id:  3911
Professor Id:  2929
Professor Id:  791
Professor Id:  220
Professor Id:  3162
Professor Id:  221
Professor Id:  1535
Professor Id:  794
Professor Id:  222
Professor Id:  4147
Professor Id:  2858
Professor Id:  223
Professor Id:  224
Professor Id:  225
Professor Id:  803
Professor Id:  1051
Professor Id:  2318
Professor Id:  763
Professor Id:  1089
Professor Id:  1906
Professor Id:  1904
Professor Id:  1165
Professor Id:  1928
Professor Id:  226
Professor Id:  787
Professor Id:  2351
Professor Id:  2419
Professor Id:  1019
Professor Id:  200
Professor Id:  2159
Professor Id:  933
Professor Id:  2802
Professor Id:  2978
Professor Id:  3018
Professor Id:  1033
Professor Id:  1201
Professor Id:  227
Professor Id:  1871
Professor Id:  228
Professor Id:  229
Professor Id:  2828
Professor Id:  4049
Professor Id:  3529
Professor Id:  2927
Professor Id:  946
Professor Id:  1426
Professor Id:  3934
Professor Id:  1302
Professor Id:  503
Professor Id:  3386
Professor Id:  2337
Professor Id:  1931
Professor Id:  230
Professor Id:  231
Professor Id:  3750
Professor Id:  232
Professor Id:  1763
Professor Id:  1785
Professor Id:  1014
Professor Id:  233
Professor Id:  234
Professor Id:  235
Professor Id:  236
Professor Id:  3996
Professor Id:  871
Professor Id:  237
Professor Id:  238
Professor Id:  240
Professor Id:  1398
Professor Id:  241
Professor Id:  242
Professor Id:  960
Professor Id:  1393
Professor Id:  243
Professor Id:  1412
Professor Id:  244
Professor Id:  1669
Professor Id:  1329
Professor Id:  1495
Professor Id:  3025
Professor Id:  3034
Professor Id:  1216
Professor Id:  245
Professor Id:  1667
Professor Id:  246
Professor Id:  247
Professor Id:  1732
Professor Id:  3468
Professor Id:  1127
Professor Id:  2610
Professor Id:  2147
Professor Id:  998
Professor Id:  248
Professor Id:  249
Professor Id:  1659
Professor Id:  2683
Professor Id:  250
Professor Id:  1496
Professor Id:  3511
Professor Id:  1537
Professor Id:  1605
Professor Id:  4038
Professor Id:  4011
Professor Id:  1429
Professor Id:  4227
Professor Id:  251
Professor Id:  2314
Professor Id:  2064
Professor Id:  252
Professor Id:  2945
Professor Id:  4207
Professor Id:  3460
Professor Id:  253
Professor Id:  1800
Professor Id:  818
Professor Id:  254
Professor Id:  802
Professor Id:  1260
Professor Id:  909
Professor Id:  1130
Professor Id:  255
Professor Id:  1322
Professor Id:  256
Professor Id:  2094
Professor Id:  2078
Professor Id:  1839
Professor Id:  1498
Professor Id:  1876
Professor Id:  4171
Professor Id:  4113
Professor Id:  257
Professor Id:  4204
Professor Id:  258
Professor Id:  910
Professor Id:  1314
Professor Id:  2619
Professor Id:  2721
Professor Id:  2662
Professor Id:  1737
Professor Id:  1326
Professor Id:  2932
Professor Id:  827
Professor Id:  1734
Professor Id:  983
Professor Id:  1112
Professor Id:  259
Professor Id:  3409
Professor Id:  2803
Professor Id:  1696
Professor Id:  260
Professor Id:  3039
Professor Id:  261
Professor Id:  1450
Professor Id:  2134
Professor Id:  262
Professor Id:  1907
Professor Id:  3071
Professor Id:  263
Professor Id:  3128
Professor Id:  1626
Professor Id:  264
Professor Id:  2924
Professor Id:  3884
Professor Id:  2062
Professor Id:  1762
Professor Id:  1639
Professor Id:  265
Professor Id:  267
Professor Id:  268
Professor Id:  269
Professor Id:  270
Professor Id:  271
Professor Id:  272
Professor Id:  1031
Professor Id:  4094
Professor Id:  3030
Professor Id:  273
Professor Id:  274
Professor Id:  1602
Professor Id:  1410
Professor Id:  3067
Professor Id:  1422
Professor Id:  2123
Professor Id:  4006
Professor Id:  1797
Professor Id:  1239
Professor Id:  275
Professor Id:  276
Professor Id:  1149
Professor Id:  3944
Professor Id:  2804
Professor Id:  277
Professor Id:  2332
Professor Id:  278
Professor Id:  4150
Professor Id:  279
Professor Id:  3950
Professor Id:  1381
Professor Id:  280
Professor Id:  2881
Professor Id:  1673
Professor Id:  2869
Professor Id:  923
Professor Id:  1339
Professor Id:  4072
Professor Id:  1367
Professor Id:  1142
Professor Id:  282
Professor Id:  2364
Professor Id:  283
Professor Id:  1486
Professor Id:  1351
Professor Id:  1232
Professor Id:  895
Professor Id:  2166
Professor Id:  943
Professor Id:  4020
Professor Id:  2736
Professor Id:  2762
Professor Id:  2791
Professor Id:  2786
Professor Id:  886
Professor Id:  2934
Professor Id:  2118
Professor Id:  284
Professor Id:  285
Professor Id:  1585
Professor Id:  1723
Professor Id:  1459
Professor Id:  286
Professor Id:  1607
Professor Id:  3717
Professor Id:  287
Professor Id:  288
Professor Id:  289
Professor Id:  1191
Professor Id:  2998
Professor Id:  290
Professor Id:  291
Professor Id:  1665
Professor Id:  1109
Professor Id:  2346
Professor Id:  292
Professor Id:  2769
Professor Id:  4067
Professor Id:  293
Professor Id:  294
Professor Id:  3710
Professor Id:  1791
Professor Id:  930
Professor Id:  2723
Professor Id:  1108
Professor Id:  295
Professor Id:  2973
Professor Id:  2485
Professor Id:  1174
Professor Id:  296
Professor Id:  1342
Professor Id:  2729
Professor Id:  1365
Professor Id:  297
Professor Id:  2936
Professor Id:  298
Professor Id:  1525
Professor Id:  3111
Professor Id:  2951
Professor Id:  299
Professor Id:  300
Professor Id:  301
Professor Id:  2892
Professor Id:  830
Professor Id:  302
Professor Id:  303
Professor Id:  2158
Professor Id:  762
Professor Id:  3003
Professor Id:  2601
Professor Id:  2111
Professor Id:  1243
Professor Id:  3492
Professor Id:  304
Professor Id:  1873
Professor Id:  1060
Professor Id:  2620
Professor Id:  305
Professor Id:  1276
Professor Id:  3083
Professor Id:  306
Professor Id:  4136
Professor Id:  2131
Professor Id:  307
Professor Id:  1857
Professor Id:  2053
Professor Id:  308
Professor Id:  309
Professor Id:  4123
Professor Id:  1389
Professor Id:  310
Professor Id:  3550
Professor Id:  311
Professor Id:  2358
Professor Id:  3024
Professor Id:  745
Professor Id:  1533
Professor Id:  3733
Professor Id:  312
Professor Id:  4149
Professor Id:  2313
Professor Id:  2316
Professor Id:  2436
Professor Id:  2701
Professor Id:  3350
Professor Id:  313
Professor Id:  2335
Professor Id:  314
Professor Id:  1308
Professor Id:  2807
Professor Id:  2816
Professor Id:  3674
Professor Id:  2087
Professor Id:  2809
Professor Id:  315
Professor Id:  1611
Professor Id:  1170

In [63]:
professor_reviews[14].head()

,Review,Grade,review_id,Course,Year,prof_id
0,Dr. Agronsky is a great professor! His class i...,N/A,47437,MATH 142,Freshman,5
0,he does not know how to teach. after waitlisti...,F,47144,MATH 142,Freshman,5
0,Dr. Agronsky was simply amazing. I was in his ...,A,41076,MATH 241,Freshman,5
0,Agronsky is a wonderful teacher. Unfortunately...,C,40991,MATH 241,Freshman,5
0,One of the best professors here at Cal Poly. T...,N/A,40806,MATH 241,Sophomore,5

# Surprise! Not all professors have a full statistical analysis page.
This code deletes professors that don't have full statistical analysis pages. Otherwise, we would have trouble merging DataFrames later on.

In [69]:
len(professor_reviews)
u_profs_previews = []
for p in professor_reviews:
    u_profs_previews.append(p.prof_id.unique()[0])
    
print(len(u_profs_previews))

u_profs_gl = []
for p in p_stats_by_grade_list:
    u_profs_gl.append(p.prof_id.unique()[0])

print(len(u_profs_gl))

no_full_stat_analyses = list(set(u_profs_previews) - set(u_profs_gl))
print(len(no_full_stat_analyses))
# no_full_stat_analyses[2]

2416
1755
661

We can get remove the professors that don't have full statistical analysis pages from the professor_reviews list of DataFrames. 

This will allow us to merge each professor_reviews DataFrame with a DataFrame from the p_stats_by_grade_list. 

The benefit of doing this is to organize grades and professor reviews into the same DataFrame.

The following code takes care of this.

In [85]:
def remove_bad_entries(): 
     '''
     Remove professors that don't have the full statistical analysis in professor_reviews list. 
     This is usually caused by having less than 5 reviews.
     Args: None
     Returns: removals (int): number of professors removed from the professor_reviews list. 
     '''
    removals = 0
    for index, p in enumerate(professor_reviews):
        if p.prof_id.values[0] in no_full_stat_analyses:
            removals += 1
            del professor_reviews[index]

    print('Removed ', removals, ' professors.')
    return removals

Removed  0  professors.

In [86]:
n = remove_bad_entries()
while n > 0:
    n = remove_bad_entries()

Removed  0  professors.

In [89]:
assert len(professor_reviews) == len(p_stats_by_grade_list)
assert u_profs_gl[-1] == u_profs_previews[-1]

# Below is time-consuming code
More webscraping is involved to get the text reviews for each professor.

In [88]:
reviews_by_grade = get_reviews_by_grade(professor_reviews, p_stats_by_grade_list)

n =  1755

In [90]:
reviews_by_grade.tail()

,Review,Grade,Course,Year,prof_id,Presents Material Clearly,Overall Rating,Recognizes Student Difficulties,Reporting Evaluations
review_id,,,,,,,,,
29816,Zumwalt's class was extremely difficult for me...,C,CHEM 124,Freshman,1758,3.667,3.667,3,3
29445,Well.. 124 is a hard class but I actually real...,C,CHEM 124,Freshman,1758,3.667,3.667,3,3
31360,"Zumwalt is alright, but she isn't the greatest...",D,CHEM 124,Sophomore,1758,2,2,2,1
29647,Before I start this is not an angry spiteful e...,N/A,CHEM 124,Freshman,1758,0.5,1,1,2
26349,You can tell she is a new teacher. She is ver...,N/A,CHEM 124,Freshman,1758,0.5,1,1,2

## Quick! Write it all to json in the /data folder under a personalized directory. Let's have two files just in case the first one ever gets corrupted.

In [91]:
create_jsons('/data/primitiveDataType/data.json', \
             [professors, p_stats, p_stats_by_grade_list, reviews_by_grade])

In [92]:
create_jsons('/data/primitiveDataType/data1.json', \
             [professors, p_stats, p_stats_by_grade_list, reviews_by_grade])